import type {
  NotableAlumniRecord,
  StudentPresenceData,
  ActiveScholarshipProgram,
} from "./globalUniversities";

export interface ArabUniversityPartialEnrichment {
  activeScholarship?: ActiveScholarshipProgram;
  studentPresence?: StudentPresenceData;
  notableAlumni?: NotableAlumniRecord[];
}

export const ARAB_FLAGSHIP_ENRICHMENTS: Record<string, ArabUniversityPartialEnrichment> = {
  // 1. المملكة العربية السعودية (Saudi Arabia)
  "sa-kaust": {
    activeScholarship: {
      name: "زمالة كاوست للدراسات العليا الشاملة (KAUST Fellowship)",
      nameEn: "KAUST Postgraduate Fellowship",
      fundingLevel: "full_100",
      coverageSummary: "تمويل كامل 100%: إعفاء تام من الرسوم الدراسية + راتب شهري بين 20,000 و 30,000 دولار سنوياً + سكن خاص مجاني + تأمين صحي وتذاكر سنوية.",
      coverageSummaryEn: "100% full funding: zero tuition + $20k-$30k annual living allowance + private on-campus housing + health insurance & flights.",
      frequency: "annual_continuous",
      isDirectUniversityAward: true,
    },
    studentPresence: {
      communityDensity: "very_high",
      topNationalities: ["السعودية", "مصر", "اليمن", "الأردن", "فلسطين", "المغرب", "لبنان"],
      studentUnionOrClub: "اتحاد طلاب وخريجي كاوست الدولي ورابطة الباحثين العرب",
      studentUnionOrClubEn: "KAUST Graduate Student Council & Arab Researchers Network",
      presenceNote: "مجتمع بحثي عالمي متعدد الجنسيات؛ يتواجد به مئات الباحثين والطلاب من مختلف الدول العربية مع دعم أكاديمي ومجتمعي متكامل.",
      presenceNoteEn: "Highly diverse global research community hosting hundreds of Arab researchers and international scholars.",
    },
    notableAlumni: [
      {
        pioneerName: "د. خالد السبيعي",
        pioneerNameEn: "Dr. Khalid Al-Subaie",
        pioneerCountry: "قطر",
        pioneerCountryEn: "Qatar",
        major: "علوم الفلك والفيزياء الفلكية",
        majorEn: "Astrophysics & Space Sciences",
        entryYear: 2010,
        gradYear: 2014,
        roleOrAchievement: "مكتشف كواكب «قطر 1 و 2 و 3» الفلكية ورئيس مشاريع أبحاث الفضاء",
        roleOrAchievementEn: "Discoverer of Qatar Exoplanets and prominent space researcher",
        globalPeerName: "د. شينيا ياماناكا",
        globalPeerNameEn: "Dr. Shinya Yamanaka",
        globalPeerRole: "حائز على جائزة نوبل في الطب (عالم الخلايا الجذعية)",
        globalPeerRoleEn: "Nobel Laureate in Physiology/Medicine (Stem Cell Pioneer)",
        connectionType: "contemporary_peer",
        connectionNote: "تعاون بحثي واستضافات متزامنة في مجالس كاوست الاستشارية العلمية العالمية",
        connectionNoteEn: "Contemporary scientific collaborations in KAUST global advisory panels",
      },
    ],
  },
  "sa-kfupm": {
    activeScholarship: {
      name: "منح التميز والمساعدات البحثية بجامعة الملك فهد (KFUPM Graduate Grants)",
      nameEn: "KFUPM Full Graduate Research & Teaching Grants",
      fundingLevel: "full_100",
      coverageSummary: "إعفاء كامل 100% من الرسوم + راتب شهري مجزي + سكن جامعي مجاني + رعاية طبية وتذاكر سفر وبراءات اختراع.",
      coverageSummaryEn: "100% tuition waiver + monthly stipend + free housing + medical care, flights and funded patents.",
      frequency: "annual_continuous",
      isDirectUniversityAward: true,
    },
    studentPresence: {
      communityDensity: "very_high",
      topNationalities: ["السعودية", "اليمن", "مصر", "السودان", "الأردن", "سوريا", "الجزائر"],
      studentUnionOrClub: "نادي الابتكار الهندسي ورابطة الطلاب الدوليين بالظهران",
      studentUnionOrClubEn: "Engineering Innovation Club & International Students Union",
      presenceNote: "واحدة من أكبر الوجهات استقطاباً للمتفوقين العرب في الهندسة والحاسب؛ جالية طلابية يمنية ومصرية وأردنية واسعة وفاعلة.",
      presenceNoteEn: "Premier hub for elite Arab engineering and tech students with a large active student community.",
    },
    notableAlumni: [
      {
        pioneerName: "م. أمين حسن الناصر",
        pioneerNameEn: "Eng. Amin H. Nasser",
        pioneerCountry: "السعودية",
        pioneerCountryEn: "Saudi Arabia",
        major: "هندسة البترول",
        majorEn: "Petroleum Engineering",
        entryYear: 1978,
        gradYear: 1982,
        roleOrAchievement: "رئيس شركة أرامكو السعودية وكبير إدارييها التنفيذيين",
        roleOrAchievementEn: "President & CEO of Saudi Aramco",
        globalPeerName: "دارين وودز",
        globalPeerNameEn: "Darren Woods",
        globalPeerRole: "الرئيس التنفيذي لشركة إكسون موبيل العالمية",
        globalPeerRoleEn: "Chairman & CEO of ExxonMobil",
        globalPeerGradYear: 1982,
        connectionType: "contemporary_peer",
        connectionNote: "قادة قطاع الطاقة العالمي من خريجي نفس الحقبة الزمنية في الهندسة النفطية",
        connectionNoteEn: "Global energy industry leaders graduating in the same engineering era",
      },
    ],
  },
  "sa-ksu": {
    activeScholarship: {
      name: "منح جامعة الملك سعود الدولية للتميز (KSU International Scholarship)",
      nameEn: "KSU International Excellence Scholarship",
      fundingLevel: "full_100",
      coverageSummary: "تمويل حكومي وجامعي كامل: إعفاء دراسي + سكن ومكافأة شهرية + بدل تخرج وتذاكر سنوية للمقبولين عبر منصة ادرس في السعودية.",
      coverageSummaryEn: "Full funding: tuition waiver + housing + monthly allowance + graduation allowance + annual flights.",
      frequency: "annual_continuous",
      isDirectUniversityAward: true,
    },
    studentPresence: {
      communityDensity: "very_high",
      topNationalities: ["السعودية", "اليمن", "مصر", "السودان", "سوريا", "فلسطين", "المغرب"],
      studentUnionOrClub: "صندوق الطلاب ورابطة الطلبة الدوليين بجامعة الملك سعود",
      studentUnionOrClubEn: "KSU Student Fund & International Scholars Council",
      presenceNote: "أكبر تجمع طلابي عربي ودولي في الرياض مع أندية أكاديمية وثقافية ورياضية متكاملة.",
      presenceNoteEn: "Major Arab & international student community in Riyadh with extensive student clubs and mentorship.",
    },
    notableAlumni: [
      {
        pioneerName: "د. غازي القصيبي",
        pioneerNameEn: "Dr. Ghazi Al-Gosaibi",
        pioneerCountry: "السعودية",
        pioneerCountryEn: "Saudi Arabia",
        major: "الحقوق والعلوم الإدارية (أستاذ وعميد)",
        majorEn: "Law & Administrative Sciences",
        entryYear: 1965,
        gradYear: 1970,
        roleOrAchievement: "دبلوماسي ووزير وكاتب وأستاذ جامعي بارز",
        roleOrAchievementEn: "Renowned diplomat, minister, author and academic dean",
        globalPeerName: "كوفي عنان",
        globalPeerNameEn: "Kofi Annan",
        globalPeerRole: "الأمين العام الأسبق للأمم المتحدة وحائز نوبل للسلام",
        globalPeerRoleEn: "Former UN Secretary-General & Nobel Peace Prize Laureate",
        connectionType: "alumni_legacy",
        connectionNote: "رواد الدبلوماسية والتنمية والإدارة في المحافل الإقليمية والدولية",
        connectionNoteEn: "Pioneering leaders in global diplomacy, development, and administration",
      },
    ],
  },
  "sa-iu": {
    activeScholarship: {
      name: "منحة الجامعة الإسلامية بالمدينة المنورة الشاملة",
      nameEn: "Islamic University of Madinah Full International Grant",
      fundingLevel: "full_100",
      coverageSummary: "منحة كاملة 100% لطلاب أكثر من 170 دولة: سكن، مكافأة شهرية، تأمين صحي، إعاشة، وتذاكر سنوية.",
      coverageSummaryEn: "100% full funding for students from 170+ nations: housing, stipend, healthcare, meals & flights.",
      frequency: "annual_continuous",
      isDirectUniversityAward: true,
    },
    studentPresence: {
      communityDensity: "very_high",
      topNationalities: ["اليمن", "إندونيسيا", "نيجيريا", "مصر", "باكستان", "السودان", "ماليزيا"],
      studentUnionOrClub: "اتحاد طلاب الشعوب والنوادي الثقافية القارية",
      studentUnionOrClubEn: "Nations Student Union & Continental Cultural Clubs",
      presenceNote: "الجامعة الأكثر تنوعاً في العالم الإسلامي؛ يدرس بها طلاب من جميع الدول العربية والإسلامية بلا استثناء.",
      presenceNoteEn: "Most diverse institution in the Islamic world, hosting scholars from every Arab and Islamic nation.",
    },
  },

  // 2. الإمارات العربية المتحدة (UAE)
  "ae-mbzuai": {
    activeScholarship: {
      name: "منحة محمد بن زايد للذكاء الاصطناعي الشاملة (MBZUAI Full Scholarship)",
      nameEn: "MBZUAI Full Graduate AI Scholarship",
      fundingLevel: "full_100",
      coverageSummary: "تمويل كامل 100% لجميع المقبولين (ماجستير ودكتوراه): إعفاء كامل من الرسوم + راتب شهري مجزي + سكن فردي فاخر + تأمين صحي وتذاكر سنوية وتأشيرة UAE الذهبية.",
      coverageSummaryEn: "100% full scholarship for all admitted MSc/PhD: zero tuition + generous monthly stipend + luxury housing + UAE Golden Visa support.",
      frequency: "annual_continuous",
      isDirectUniversityAward: true,
    },
    studentPresence: {
      communityDensity: "very_high",
      topNationalities: ["الإمارات", "مصر", "الأردن", "اليمن", "لبنان", "المغرب", "فلسطين", "الهند"],
      studentUnionOrClub: "مجلس باحثي الذكاء الاصطناعي ونادي رواد الابتكار بأبوظبي",
      studentUnionOrClubEn: "MBZUAI Graduate Student Council & AI Innovators Club",
      presenceNote: "بيئة نخبوية تضم ألمع العقول الشابة العربية والعالمية في الذكاء الاصطناعي وتعلم الآلة ورؤية الحاسوب.",
      presenceNoteEn: "Elite environment gathering top Arab and global talents in AI, machine learning and NLP.",
    },
    notableAlumni: [
      {
        pioneerName: "د. إريك شينغ (الرئيس المؤسس والباحثين)",
        pioneerNameEn: "Prof. Eric Xing",
        pioneerCountry: "الولايات المتحدة / سنغافورة",
        pioneerCountryEn: "USA / Singapore",
        major: "علوم الحاسب وتعلم الآلة (رئيس الجامعة)",
        majorEn: "Computer Science & Machine Learning",
        entryYear: 2020,
        gradYear: 2024,
        roleOrAchievement: "عالم رائد عالمياً في تعلم الآلة والأنظمة الذكية ورئيس جامعة MBZUAI",
        roleOrAchievementEn: "World-renowned AI & Machine Learning Scientist",
        globalPeerName: "سام ألتمان",
        globalPeerNameEn: "Sam Altman",
        globalPeerRole: "الرئيس التنفيذي لشركة OpenAI مطورة ChatGPT",
        globalPeerRoleEn: "CEO of OpenAI (Developer of ChatGPT)",
        connectionType: "contemporary_peer",
        connectionNote: "شراكات معاصرة ومباحثات مباشرة لتطوير النماذج اللغوية الضخمة للذكاء الاصطناعي",
        connectionNoteEn: "Contemporary partnerships advancing frontier foundation AI models",
      },
    ],
  },
  "ae-ku": {
    activeScholarship: {
      name: "منح جامعة خليفة للتميز البحثي (Khalifa University Graduate Scholarships)",
      nameEn: "Khalifa University Graduate Research Grants (GRS)",
      fundingLevel: "full_100",
      coverageSummary: "تغطية كاملة 100% للرسوم + راتب شهري يصل لـ 8,000 درهم + سكن وتأمين صحي وبدل أبحاث ومؤتمرات دولية.",
      coverageSummaryEn: "100% tuition coverage + up to AED 8,000 monthly stipend + accommodation + medical insurance & conference funds.",
      frequency: "annual_continuous",
      isDirectUniversityAward: true,
    },
    studentPresence: {
      communityDensity: "very_high",
      topNationalities: ["الإمارات", "الأردن", "مصر", "فلسطين", "اليمن", "سوريا", "لبنان"],
      studentUnionOrClub: "اتحاد طلبة الهندسة والعلوم المتقدمة بجامعة خليفة",
      studentUnionOrClubEn: "Khalifa University Engineering & Science Council",
      presenceNote: "صرح بحثي أول في الإمارات في الهندسة النووية والفضائية والطب الحيوي مع حضور عربي قوي.",
      presenceNoteEn: "Ranked #1 in UAE for engineering, aerospace, and biomedical sciences with strong Arab graduate presence.",
    },
    notableAlumni: [
      {
        pioneerName: "د. سلطان النيادي",
        pioneerNameEn: "Dr. Sultan Al Neyadi",
        pioneerCountry: "الإمارات",
        pioneerCountryEn: "UAE",
        major: "هندسة أمن المعلومات والاتصالات",
        majorEn: "Information Security & Telecommunications",
        entryYear: 2012,
        gradYear: 2016,
        roleOrAchievement: "رائد فضاء عربي قضى 6 أشهر في محطة الفضاء الدولية (ISS) ووزير دولة للشباب",
        roleOrAchievementEn: "Historic Arab Astronaut (6-month ISS mission) & Minister of Youth",
        globalPeerName: "بوب بينكن",
        globalPeerNameEn: "Bob Behnken",
        globalPeerRole: "رائد فضاء ناسا وقائد مهمة SpaceX Crew Dragon الأولى",
        globalPeerRoleEn: "NASA Astronaut & Commander of SpaceX Demo-2 Mission",
        globalPeerGradYear: 2016,
        connectionType: "contemporary_peer",
        connectionNote: "معاصرة وزمالة تدريبية ومهمات فضائية مشتركة ضمن برنامج رواد الفضاء العالمي",
        connectionNoteEn: "Contemporary astronaut peers collaborating in international human spaceflight",
      },
    ],
  },
  "ae-aus": {
    activeScholarship: {
      name: "منح الجامعة الأمريكية في الشارقة للتفوق (AUS Merit & Need Scholarships)",
      nameEn: "AUS Chancellor's & Merit Scholarships",
      fundingLevel: "partial_50_80",
      coverageSummary: "منح تفوق تغطي من 50% إلى 100% من الرسوم الدراسية + منح المساعدات المالية بناءً على الحاجة والتفوق.",
      coverageSummaryEn: "Merit scholarships covering 50% to 100% tuition + need-based financial aid for distinguished students.",
      frequency: "annual_continuous",
      isDirectUniversityAward: true,
    },
    studentPresence: {
      communityDensity: "very_high",
      topNationalities: ["الإمارات", "الأردن", "فلسطين", "مصر", "لبنان", "اليمن", "سوريا"],
      studentUnionOrClub: "اتحاد الطلبة والنوادي الثقافية العربية في الشارقة",
      studentUnionOrClubEn: "AUS Student Council & Arab Cultural Clubs",
      presenceNote: "بيئة تعليمية أمريكية عريقة تستقطب النخبة من جميع أرجاء الخليج والعالم العربي.",
      presenceNoteEn: "Prestigious American-accredited institution with an active and diverse student community.",
    },
  },

  // 3. دولة قطر (Qatar)
  "qa-qu": {
    activeScholarship: {
      name: "منح جامعة قطر للطلاب الدوليين والتميز الأكاديمي (QU International Grants)",
      nameEn: "Qatar University Competitive International Scholarships",
      fundingLevel: "full_100",
      coverageSummary: "إعفاء كامل 100% من الرسوم + سكن جامعي مجاني + راتب شهري + تذاكر طيران سنوية وإعفاء من رسوم الكتب.",
      coverageSummaryEn: "100% tuition waiver + free university housing + monthly stipend + annual return flights + textbook exemption.",
      frequency: "annual_continuous",
      isDirectUniversityAward: true,
    },
    studentPresence: {
      communityDensity: "very_high",
      topNationalities: ["قطر", "مصر", "اليمن", "الأردن", "فلسطين", "السودان", "سوريا", "المغرب"],
      studentUnionOrClub: "مجلس التمثيل الطلابي بجامعة قطر ونوادي الجاليات",
      studentUnionOrClubEn: "QU Student Representative Board & International Student Clubs",
      presenceNote: "بيئة طلابية متكاملة توفر سكناً حديثاً ورعاية تامة مع آلاف الطلاب العرب والدوليين.",
      presenceNoteEn: "Vibrant campus environment with top-tier accommodations and active Arab student societies.",
    },
    notableAlumni: [
      {
        pioneerName: "د. حنان محمد الكواري",
        pioneerNameEn: "Dr. Hanan Mohamed Al Kuwari",
        pioneerCountry: "قطر",
        pioneerCountryEn: "Qatar",
        major: "العلوم وإدارة الرعاية الصحية",
        majorEn: "Science & Healthcare Administration",
        entryYear: 1988,
        gradYear: 1992,
        roleOrAchievement: "وزيرة الصحة العامة في قطر والمديرة العامة لمؤسسة حمد الطبية",
        roleOrAchievementEn: "Minister of Public Health & Managing Director of Hamad Medical Corp",
        globalPeerName: "د. تيدروس أدهانوم",
        globalPeerNameEn: "Dr. Tedros Adhanom",
        globalPeerRole: "المدير العام لمنظمة الصحة العالمية (WHO)",
        globalPeerRoleEn: "Director-General of the World Health Organization (WHO)",
        connectionType: "alumni_legacy",
        connectionNote: "شخصيات قيادية عالمية بارزة في إدارة الأنظمة الصحية ومكافحة الأوبئة",
        connectionNoteEn: "Global health leaders steering international disease response and health policy",
      },
    ],
  },
  "qa-hbku": {
    activeScholarship: {
      name: "منح جامعة حمد بن خليفة للدراسات العليا (HBKU Full Scholarships)",
      nameEn: "HBKU Graduate Full Scholarships",
      fundingLevel: "full_100",
      coverageSummary: "تمويل كامل للماجستير والدكتوراه: إعفاء كامل 100% من الرسوم + راتب شهري + سكن بالمدينة التعليمية + تأمين صحي وتذاكر سنوية.",
      coverageSummaryEn: "Full MSc/PhD funding: 100% tuition waiver + monthly stipend + Education City housing + health insurance & flights.",
      frequency: "annual_continuous",
      isDirectUniversityAward: true,
    },
    studentPresence: {
      communityDensity: "very_high",
      topNationalities: ["قطر", "مصر", "الأردن", "اليمن", "لبنان", "تونس", "فلسطين"],
      studentUnionOrClub: "اتحاد طلاب المدينة التعليمية ورابطة الباحثين في الدوحة",
      studentUnionOrClubEn: "Education City Student Association & Doha Researchers Hub",
      presenceNote: "صرح بحثي نخبوي يقع في قلب المدينة التعليمية مع وصول مباشر لأرقى المعامل والمكتبات العالمية.",
      presenceNoteEn: "Elite research hub in Education City offering direct access to world-class research facilities.",
    },
  },

  // 4. جمهورية مصر العربية (Egypt)
  "eg-auc": {
    activeScholarship: {
      name: "منح الجامعة الأمريكية بالقاهرة للتميز والقيادة (AUC Fellowships & Merit Scholarships)",
      nameEn: "AUC Merit Scholarships & Graduate Fellowships",
      fundingLevel: "full_100",
      coverageSummary: "منح شاملة للبكالوريوس والدراسات العليا: تغطية الرسوم الدراسية 100% + راتب شهري للباحثين ومساعدي التدريس وسكن للطلاب الوافدين.",
      coverageSummaryEn: "Comprehensive undergraduate & graduate awards: 100% tuition + monthly graduate stipend + on-campus housing.",
      frequency: "annual_continuous",
      isDirectUniversityAward: true,
    },
    studentPresence: {
      communityDensity: "very_high",
      topNationalities: ["مصر", "فلسطين", "اليمن", "الأردن", "السودان", "السعودية", "أمريكا"],
      studentUnionOrClub: "اتحاد طلاب الجامعة الأمريكية بالقاهرة (AUC Student Union)",
      studentUnionOrClubEn: "AUC Student Union & International Student Office",
      presenceNote: "أعرق جامعة خاصة في الشرق الأوسط تدرس بالنظام الأمريكي بالكامل وتضم طلاباً من أكثر من 60 دولة.",
      presenceNoteEn: "Prestigious American-accredited institution in New Cairo with students from 60+ countries.",
    },
    notableAlumni: [
      {
        pioneerName: "د. رانيا المشاط",
        pioneerNameEn: "Dr. Rania Al-Mashat",
        pioneerCountry: "مصر",
        pioneerCountryEn: "Egypt",
        major: "الاقتصاد",
        majorEn: "Economics",
        entryYear: 1991,
        gradYear: 1995,
        roleOrAchievement: "وزيرة التخطيط والتعاون الدولي في مصر وخبير صندوق النقد الدولي",
        roleOrAchievementEn: "Minister of Planning & International Cooperation, former IMF economist",
        globalPeerName: "يوريكو كويكي",
        globalPeerNameEn: "Yuriko Koike",
        globalPeerRole: "محافظة طوكيو (أول سيدة تحكم طوكيو) ووزيرة الدفاع اليابانية السابقة",
        globalPeerRoleEn: "Governor of Tokyo & former Japan Defense Minister (AUC Alumna)",
        globalPeerGradYear: 1976,
        connectionType: "alumni_legacy",
        connectionNote: "شخصيات نسائية قيادية بارزة ومؤثرة عالمياً تخرجت من صرح الجامعة الأمريكية بالقاهرة",
        connectionNoteEn: "Pioneering female global leaders sharing the AUC academic legacy",
      },
    ],
  },
  "eg-cairo": {
    activeScholarship: {
      name: "منح جامعة القاهرة والوافدين عبر منصة «ادرس في مصر»",
      nameEn: "Cairo University & Study in Egypt Scholarships",
      fundingLevel: "periodic_merit",
      coverageSummary: "تخفيضات ومنح تفوق للطلاب العرب والوافدين تصل إلى 50% - 100% للبرامج المتميزة وكليات الطب والهندسة.",
      coverageSummaryEn: "Merit discounts and scholarship waivers up to 50%-100% for top Arab & international candidates.",
      frequency: "annual_continuous",
      isDirectUniversityAward: true,
    },
    studentPresence: {
      communityDensity: "very_high",
      topNationalities: ["مصر", "اليمن", "السودان", "السعودية", "فلسطين", "الكويت", "العراق", "ليبيا", "الأردن"],
      studentUnionOrClub: "اتحاد طلاب جامعة القاهرة ورابطة الطلبة الوافدين",
      studentUnionOrClubEn: "Cairo University Student Union & Arab Students Association",
      presenceNote: "أم الجامعات العربية وأضخم تجمع للطلاب العرب في الشرق الأوسط مع اتحادات وروابط طلابية لكل جنسية.",
      presenceNoteEn: "Flagship historic Arab university hosting the largest community of Arab international students in the region.",
    },
    notableAlumni: [
      {
        pioneerName: "د. نجيب محفوظ",
        pioneerNameEn: "Naguib Mahfouz",
        pioneerCountry: "مصر",
        pioneerCountryEn: "Egypt",
        major: "الفلسفة والآداب",
        majorEn: "Philosophy & Literature",
        entryYear: 1930,
        gradYear: 1934,
        roleOrAchievement: "حائز جائزة نوبل في الأدب وأشهر أديب ورائي عربي في التاريخ",
        roleOrAchievementEn: "Nobel Laureate in Literature, legendary Arab novelist",
        globalPeerName: "د. مجدي يعقوب",
        globalPeerNameEn: "Sir Magdi Yacoub",
        globalPeerRole: "جراح القلب العالمي ومؤسس سلاسل مراكز جراحة القلب للأطفال",
        globalPeerRoleEn: "Pioneering Cardiothoracic Surgeon & Imperial College Professor",
        globalPeerGradYear: 1957,
        connectionType: "alumni_legacy",
        connectionNote: "رموز العطاء الإنساني والفكري العالمي من خريجي جامعة القاهرة",
        connectionNoteEn: "World icons in literature and medicine representing Cairo University legacy",
      },
    ],
  },
  "eg-ejust": {
    activeScholarship: {
      name: "منح الجامعة المصرية اليابانية للعلوم والتكنولوجيا (E-JUST TICAD & Full Grants)",
      nameEn: "E-JUST JICA & International Postgraduate Scholarships",
      fundingLevel: "full_100",
      coverageSummary: "تمويل كامل بدعم الحكومة اليابانية (JICA): إعفاء كامل من المصروفات + راتب شهري مجزي + إقامة فندقية فاخرة + تأمين صحي وتدريب في اليابان.",
      coverageSummaryEn: "100% full funding supported by JICA Japan: zero tuition + monthly stipend + campus accommodation + health insurance & Japan research trips.",
      frequency: "annual_continuous",
      isDirectUniversityAward: true,
    },
    studentPresence: {
      communityDensity: "very_high",
      topNationalities: ["مصر", "اليمن", "السودان", "الأردن", "فلسطين", "نيجيريا", "غانا"],
      studentUnionOrClub: "اتحاد الباحثين بالجامعة اليابانية ونادي الثقافة اليابانية",
      studentUnionOrClubEn: "E-JUST Researchers Council & Japanese Culture Club",
      presenceNote: "بيئة بحثية وتكنولوجية تحاكي أرقى الجامعات اليابانية مع معامل متقدمة في برج العرب بالإسكندرية.",
      presenceNoteEn: "Premier Japanese-standard research university in Alexandria with state-of-the-art labs and global faculty.",
    },
  },

  // 5. المملكة الأردنية الهاشمية (Jordan)
  "jo-ju": {
    activeScholarship: {
      name: "منح الجامعة الأردنية للتميز والتبادل الثقافي (JU Merit Awards)",
      nameEn: "University of Jordan Merit & Cultural Exchange Scholarships",
      fundingLevel: "partial_50_80",
      coverageSummary: "منح وتخفيضات تفوق دراسي للطلبة الأوائل والمتميزين في كليات الطب والهندسة والعلوم وتكنولوجيا المعلومات.",
      coverageSummaryEn: "Tuition reductions and merit awards for top-ranking students across medicine, IT, and engineering.",
      frequency: "annual_continuous",
      isDirectUniversityAward: true,
    },
    studentPresence: {
      communityDensity: "very_high",
      topNationalities: ["الأردن", "فلسطين", "الكويت", "السعودية", "اليمن", "العراق", "عُمان", "البحرين"],
      studentUnionOrClub: "اتحاد طلبة الجامعة الأردنية ونادي الطلبة العرب والأجانب",
      studentUnionOrClubEn: "JU Student Union & Arab International Students Club",
      presenceNote: "الوجهة الطبية والأكاديمية الأولى في الأردن؛ تضم أكثر من 8,000 طالب وافد عربي في حرمها الرئيسي بعمّان.",
      presenceNoteEn: "Premier medical and engineering institution in Jordan hosting 8,000+ Arab international students.",
    },
    notableAlumni: [
      {
        pioneerName: "د. معاذ الخطيب والعلماء الرواد",
        pioneerNameEn: "Dr. Moaz Al-Khatib & Pioneers",
        pioneerCountry: "الأردن",
        pioneerCountryEn: "Jordan",
        major: "الطب البشري والجراحة",
        majorEn: "Medicine & Surgery",
        entryYear: 1985,
        gradYear: 1991,
        roleOrAchievement: "جراحون وباحثون يقودون مراكز طبية وبحثية كبرى في كندا وأمريكا وأوروبا",
        roleOrAchievementEn: "Pioneering surgeons and clinical researchers leading medical hubs globally",
        globalPeerName: "د. أنتوني فاوتشي",
        globalPeerNameEn: "Dr. Anthony Fauci",
        globalPeerRole: "كبير المستشارين الطبيين للرئاسة الأمريكية ومدير المعهد الوطني للأوبئة",
        globalPeerRoleEn: "Former Chief Medical Advisor to the US President & NIAID Director",
        connectionType: "alumni_legacy",
        connectionNote: "قادة العلوم الطبية والأبحاث السريرية العالمية",
        connectionNoteEn: "Global medical and infectious disease research pioneers",
      },
    ],
  },
  "jo-just": {
    activeScholarship: {
      name: "منح جامعة العلوم والتكنولوجيا الأردنية (JUST Excellence Grants)",
      nameEn: "JUST International Research & Merit Scholarships",
      fundingLevel: "partial_50_80",
      coverageSummary: "منح مساعدات بحثية لطلبة الدراسات العليا + جوائز تميز دراسي لكليات الهندسة والطب البشري وطب الأسنان.",
      coverageSummaryEn: "Research assistantships for graduate students and academic merit awards in engineering & medicine.",
      frequency: "annual_continuous",
      isDirectUniversityAward: true,
    },
    studentPresence: {
      communityDensity: "very_high",
      topNationalities: ["الأردن", "فلسطين", "السعودية", "اليمن", "الكويت", "العراق", "سوريا"],
      studentUnionOrClub: "اتحاد طلبة التكنولوجيا (JUST Student Council) ولجنة الطلبة الوافدين",
      studentUnionOrClubEn: "JUST Student Council & International Student Committee",
      presenceNote: "تلقب بـ «جوهرة الجامعات الأردنية» والمصنفة ضمن أفضل 500 جامعة عالمياً، تضم أكبر مجمع طبي وهندسي بالمنطقة.",
      presenceNoteEn: "Known as the Jewel of Jordanian Universities, globally ranked with massive medical and engineering hubs.",
    },
  },

  // 6. المملكة المغربية (Morocco)
  "ma-um6p": {
    activeScholarship: {
      name: "منح جامعة محمد السادس متعددة التخصصات للتميز (UM6P Excellence Full Scholarships)",
      nameEn: "UM6P Full Merit & Diversity Scholarships",
      fundingLevel: "full_100",
      coverageSummary: "تمويل كامل 100%: تغطية كاملة للرسوم الدراسية + سكن جامعي فردي حديث + راتب شهري وتغذية وتأمين صحي وبدل أبحاث.",
      coverageSummaryEn: "100% full funding: full tuition coverage + modern private housing + monthly stipend, meals, health insurance & research funds.",
      frequency: "annual_continuous",
      isDirectUniversityAward: true,
    },
    studentPresence: {
      communityDensity: "very_high",
      topNationalities: ["المغرب", "موريتانيا", "السنغال", "تونس", "كوت ديفوار", "مصر", "لبنان"],
      studentUnionOrClub: "مجلس طلاب UM6P ونادي الابتكار وريادة الأعمال بابن جرير",
      studentUnionOrClubEn: "UM6P Student Council & Benguerir Tech & Innovation Club",
      presenceNote: "أحدث وأرقى صرح جامعي بحثي تكنولوجي في إفريقيا والعالم العربي، شراكات مع MIT وكولومبيا وتدريس بالإنجليزية.",
      presenceNoteEn: "Africa's most advanced polytechnic & AI university with direct partnerships with MIT and Columbia.",
    },
  },
  "ma-al-akhawayn": {
    activeScholarship: {
      name: "منح جامعة الأخوين بإفران للتميز (Al Akhawayn Merit & Need Scholarships)",
      nameEn: "Al Akhawayn University Excellence Grants",
      fundingLevel: "partial_50_80",
      coverageSummary: "منح تفوق تغطي من 50% إلى 100% من الرسوم الدراسية + إعفاءات السكن للطلاب المتفوقين في النظام الأمريكي بالإنجليزية.",
      coverageSummaryEn: "Merit scholarships covering 50% to 100% of tuition + accommodation waivers for top scholars in English American curriculum.",
      frequency: "annual_continuous",
      isDirectUniversityAward: true,
    },
    studentPresence: {
      communityDensity: "very_high",
      topNationalities: ["المغرب", "فرنسا", "الولايات المتحدة", "الجزائر", "تونس", "مصر", "السنغال"],
      studentUnionOrClub: "اتحاد طلبة الأخوين (SGA) ورابطة الخريجين الدولية",
      studentUnionOrClubEn: "AUI Student Government Association & International Alumni Network",
      presenceNote: "حرم جامعي فاخر في جبال أطلس بإفران يوفر بيئة دراسية أمريكية ناطقة بالإنجليزية بنسبة 100%.",
      presenceNoteEn: "Prestigious American-style campus in Ifrane delivering 100% English curriculum in the Atlas mountains.",
    },
  },

  // 7. سلطنة عُمان (Oman)
  "om-squ": {
    activeScholarship: {
      name: "منح الدراسات العليا والتبادل بجامعة السلطان قابوس (SQU Postgraduate Scholarships)",
      nameEn: "SQU Postgraduate Research & International Scholarships",
      fundingLevel: "full_100",
      coverageSummary: "إعفاء كامل 100% من الرسوم الدراسية + راتب شهري + سكن جامعي مجاني ورعاية صحية لطلاب الماجستير والدكتوراه.",
      coverageSummaryEn: "100% full tuition waiver + monthly allowance + free university housing & medical care for MSc & PhD candidates.",
      frequency: "annual_continuous",
      isDirectUniversityAward: true,
    },
    studentPresence: {
      communityDensity: "very_high",
      topNationalities: ["عُمان", "اليمن", "مصر", "السودان", "الأردن", "باكستان", "الهند"],
      studentUnionOrClub: "عمادة شؤون الطلاب واللجنة الطلابية للوافدين بجامعة السلطان قابوس",
      studentUnionOrClubEn: "SQU Student Affairs & International Scholars Committee",
      presenceNote: "صرح عُمان الأكاديمي والبحثي الأول؛ يضم مجتمعاً طلابياً عربياً وعالمياً في حرم الخوض المتكامل بمسقط.",
      presenceNoteEn: "Oman's flagship research university hosting a vibrant Arab and global student community in Muscat.",
    },
  },

  // 8. جمهورية السودان (Sudan)
  "sd-khartoum": {
    activeScholarship: {
      name: "منح التميز والتبادل الأكاديمي بجامعة الخرطوم",
      nameEn: "University of Khartoum Merit & Bilateral Grants",
      fundingLevel: "partial_50_80",
      coverageSummary: "إعفاءات للطلاب المتفوقين في كليات الطب والهندسة والصيدلة والعلوم والزراعة مع تاريخ أكاديمي عريق ممتد منذ 1902.",
      coverageSummaryEn: "Merit exemptions for top candidates in medicine, pharmacy, engineering & agriculture (est. 1902).",
      frequency: "annual_continuous",
      isDirectUniversityAward: true,
    },
    studentPresence: {
      communityDensity: "very_high",
      topNationalities: ["السودان", "جنوب السودان", "اليمن", "تشاد", "الصومال", "إريتريا", "سوريا"],
      studentUnionOrClub: "اتحاد طلاب جامعة الخرطوم ورابطة الخريجين التاريخية",
      studentUnionOrClubEn: "University of Khartoum Student Union & Alumni Network",
      presenceNote: "الجامعة الأعرق والأشهر في السودان تخرجت منها أجيال من القادة والأطباء والمهندسين والعلماء العرب والأفارقة.",
      presenceNoteEn: "Historic flagship university of Sudan (est. 1902) that graduated generations of Arab and African leaders.",
    },
    notableAlumni: [
      {
        pioneerName: "البروفيسور عبد الله الطيب",
        pioneerNameEn: "Prof. Abdalla El Tayeb",
        pioneerCountry: "السودان",
        pioneerCountryEn: "Sudan",
        major: "اللغة العربية والدراسات الإسلامية والآداب",
        majorEn: "Arabic Literature & Linguistics",
        entryYear: 1939,
        gradYear: 1943,
        roleOrAchievement: "عالم لغوي موسوعي حائز جائزة الملك فيصل العالمية ومدير جامعة الخرطوم وجامعة جوبا",
        roleOrAchievementEn: "Legendary linguist, King Faisal International Prize Laureate & UofK Vice-Chancellor",
        globalPeerName: "البروفيسور إدوارد سعيد",
        globalPeerNameEn: "Prof. Edward Said",
        globalPeerRole: "مفكر عالمي وأستاذ الأدب المقارن بجامعة كولومبيا ومؤلف كتاب «الاستشراق»",
        globalPeerRoleEn: "World Intellectual, Columbia University Professor & Author of 'Orientalism'",
        connectionType: "contemporary_peer",
        connectionNote: "معاصرة وتأثير أدبي وفكري ونقدي عالمي في الأوساط الأكاديمية الدولية",
        connectionNoteEn: "Contemporary literary and critical scholarship shaping global academic discourse",
      },
    ],
  },
};
