import { createContext, useContext, useEffect, useState, ReactNode, useCallback } from "react";
import { COUNTRIES } from "@/lib/countries";

export type Lang = "ar" | "en";

interface LanguageCtx {
  lang: Lang;
  dir: "rtl" | "ltr";
  setLang: (l: Lang) => void;
  toggleLang: () => void;
  t: (key: string) => string;
}

const STRINGS: Record<Lang, Record<string, string>> = {
  ar: {
    settings: "الإعدادات",
    darkMode: "الوضع الليلي",
    accountSettings: "إعدادات الحساب",
    privacy: "الخصوصية والأمان",
    about: "حول التطبيق",
    clearCache: "مسح الملفات المؤقتة",
    shareApp: "مشاركة التطبيق",
    logout: "تسجيل الخروج",
    language: "اللغة",
    arabic: "العربية",
    english: "English",
    notifications: "الإشعارات",
    confirmLogout: "تأكيد تسجيل الخروج",
    confirmLogoutDesc: "هل أنت متأكد أنك تريد الخروج من حسابك؟",
    yesLogout: "نعم، اخرج",
    cancel: "إلغاء",
    privacyTitle: "سياسة الخصوصية والأمان",
    privacyBody:
      "نحن نلتزم بحماية بياناتك الشخصية. لا نشارك معلوماتك مع أطراف ثالثة دون إذنك. تُخزّن البيانات الحساسة بشكل مشفّر، ويُستخدم بريدك الإلكتروني فقط لتسجيل الدخول والإشعارات. يمكنك حذف حسابك وبياناتك في أي وقت من إعدادات الحساب.",
    close: "إغلاق",
    // Tabs
    tabScholarships: "المنح والفرص",
    tabNews: "الأخبار والاقتصاد",
    tabCurrency: "العملات",
    tabApplications: "طلباتي",
    tabProfile: "الملف الشخصي",
    tabJobs: "فرص العمل",
    tabArabUnis: "الجامعات العربية",
    // Arab universities
    arabUniTitle: "دليل الجامعات العربية",
    arabUniSubtitle: "أكثر من 30 جامعة في 20 دولة عربية مع شروط القبول والمنح المتاحة.",
    arabUniSearch: "ابحث باسم الجامعة أو الدولة أو المدينة...",
    arabUniMatchTitle: "المطابقة الذكية بنسبتك",
    arabUniPctPlaceholder: "نسبتك %",
    arabUniEligibleOnly: "المؤهلة فقط",
    arabUniEligibleCount: "أنت مؤهل لـ {n} جامعة حسب نسبتك.",
    arabUniAllCountries: "كل الدول",
    arabUniAllFaculties: "كل الكليات",
    arabUniResults: "{n} نتيجة",
    arabUniGov: "حكومية",
    arabUniPrivate: "خاصة",
    arabUniHasScholarships: "منح متاحة",
    arabUniMin: "الحد الأدنى",
    arabUniEmpty: "لا توجد جامعات مطابقة لبحثك.",
    arabUniCity: "المدينة",
    arabUniType: "النوع",
    arabUniLanguage: "لغة الدراسة",
    arabUniFaculties: "الكليات والتخصصات",
    arabUniVisit: "زيارة الموقع الرسمي",
    arabUniCountriesTitle: "اختر الدولة",
    arabUniYourCountry: "دولتك",
    arabUniUnisCount: "{n} جامعة",
    arabUniBack: "رجوع للدول",
    arabUniCompare: "مقارنة",
    arabUniCompareHint: "اختر حتى 3 جامعات للمقارنة",
    arabUniCompareOpen: "عرض المقارنة ({n})",
    arabUniClear: "إلغاء التحديد",
    arabUniTuition: "الرسوم الدراسية",
    arabUniLiving: "تكلفة المعيشة",
    arabUniSeasons: "مواعيد التقديم",
    arabUniDocs: "المستندات المطلوبة",
    arabUniSteps: "خطوات التقديم",
    arabUniMap: "الموقع على الخريطة",
    arabUniOverview: "نظرة عامة",
    arabUniCosts: "التكاليف",
    arabUniAdmission: "القبول",
    // Notifications
    notifMatchTitle: "مطابقة ذكية جديدة",
    notifMatchBody: "وجدنا 3 منح تطابق مهاراتك بناءً على أحدث الأخبار العالمية.",
    notifDeadlineTitle: "اقترب الموعد النهائي",
    notifDeadlineBody: "منحة تشيفنينغ تنتهي خلال 14 يوماً. لا تفوّت الفرصة.",
    notifNewsTitle: "خبر يربطك بفرصة",
    notifNewsBody: "الاتحاد الأوروبي وسّع برامج إيراسموس — تحقق من الفرص الجديدة.",
    timeMinutesAgo: "قبل دقائق",
    timeHourAgo: "قبل ساعة",
    time3HoursAgo: "قبل 3 ساعات",
    notifFooter: "الإشعارات تربط الأخبار العالمية بالفرص المناسبة لملفك الشخصي.",
    // Scholarships
    scholarshipsHint: "الفرص مجمّعة من مصادر رسمية عالمية وعربية، ومُرتّبة حسب موقعك واهتماماتك.",
    aiMatchBadge: "مطابقة ذكية جديدة",
    aiMatchBody: "وجدنا 3 منح تطابق مهاراتك بناءً على تحليل أحدث الأخبار العالمية",
    swipeHint: "اسحب لليمين للحفظ • لليسار للتجاهل",
    noMoreScholarships: "انتهت المنح المتاحة",
    noMoreScholarshipsDesc: "سنخبرك حال توفر منح جديدة تناسبك",
    reload: "إعادة التحميل",
    filterArabScholarships: "المنح العربية",
    filterGlobalScholarships: "المنح العالمية",
    studyLanguage: "لغة الدراسة",
    langArabic: "العربية",
    langEnglish: "الإنجليزية",
    langBoth: "عربي/إنجليزي",
    noScholarshipsCategory: "لا توجد منح في هذا التصنيف حالياً",
    verified: "موثقة",
    manualReview: "مراجعة يدوية",
    matchPercent: "مناسبة لك بنسبة",
    country: "الدولة",
    amount: "المبلغ",
    deadline: "آخر موعد",
    level: "المستوى",
    applyOfficial: "التقديم على الموقع الرسمي",
    applyOfficialNote: "سيتم فتح الموقع الرسمي للجهة المانحة داخل التطبيق لتقديم طلبك مباشرة.",
    sourceLink: "رابط المصدر",
    saved: "تم حفظ المنحة في طلباتك",
    dismissed: "تم تجاهل المنحة",
    // News
    dataSaver: "وضع توفير البيانات (نص فقط)",
    catAll: "الكل",
    catLocal: "محلي",
    catArab: "عربي",
    catGlobal: "عالمي",
    lastUpdated: "آخر تحديث",
    loadingShort: "جارٍ التحميل...",
    newsCount: "خبر",
    openSource: "افتح المصدر",
    // Weather
    searchCityPlaceholder: "ابحث عن طقس مدينة أخرى...",
    search: "بحث",
    cityNotFound: "لم يتم العثور على المدينة",
    weatherFailed: "تعذر تحديث الطقس",
    loadingWeather: "جارٍ تحميل الطقس...",
    // Currency Calculator
    liveGoldCurrency: "حاسبة العملات والذهب الحية",
    calc: "حاسبة",
    currency: "العملات",
    gold: "الذهب",
    from: "من",
    to: "إلى",
    weight: "الوزن (غ)",
    karat: "العيار",
    estValue: "القيمة التقديرية",
    fetchingRates: "جارٍ جلب أحدث الأسعار...",
    liveRatesAt: "أسعار حية — آخر تحديث",
    fetchingGold: "جارٍ جلب سعر الذهب...",
    liveGoldAt: "سعر الذهب الحي — آخر تحديث",
    // Applications
    loading: "جاري التحميل...",
    noApps: "لا توجد طلبات بعد",
    noAppsDesc: "ابدأ بحفظ المنح من قسم \"المنح والفرص\"",
    statusApplied: "متقدّم",
    statusSaved: "محفوظة",
    markApplied: "علّم كمتقدّم",
    markedApplied: "تم وضع علامة كمتقدّم",
    updated: "تم التحديث",
    removed: "تمت الإزالة",
    // Profile
    fullName: "الاسم الكامل",
    location: "الموقع",
    bio: "نبذة",
    education: "التعليم",
    interests: "الاهتمامات الأساسية",
    skills: "المهارات",
    addSkill: "أضف مهارة...",
    noSkills: "لم تُضِف مهارات بعد",
    save: "حفظ التغييرات",
    saving: "جاري الحفظ...",
    saveFailed: "تعذر الحفظ",
    saved2: "تم حفظ ملفك الشخصي",
    edit: "تعديل",
    editProfile: "تعديل الملف الشخصي",
    editProfileDesc: "حدّث بياناتك للحصول على فرص أنسب",
    profileCompletion: "اكتمال الملف الشخصي",
    completeProfileHint: "أكمل بياناتك للحصول على مطابقات أدق للمنح والفرص.",
    personalInfo: "المعلومات الشخصية",
    interestsHint: "تُستخدم لمطابقتك بالمنح والفرص الأنسب لك.",
    yourNameHolder: "اكتب اسمك",
    locationHolder: "المدينة، الدولة",
    bioHolder: "عرّف عن نفسك...",
    eduHolder: "مثال: بكالوريوس هندسة حاسوب، جامعة الملك سعود، 2024",
    eduLabel: "المؤهل التعليمي",
    idCard: "FORAS · ID CARD",
    yourFullName: "اسمك الكامل",
    eduDetailsTitle: "المعلومات التعليمية",
    highSchoolLabel: "المدرسة الثانوية",
    highSchoolHolder: "اسم المدرسة الثانوية...",
    universityLabel: "الجامعة / الكلية",
    universityHolder: "اسم الجامعة أو الكلية...",
    majorLabel: "التخصص الدراسي",
    majorHolder: "التخصص...",
    gpaLabel: "المعدل التراكمي",
    gpaScaleLabel: "السلّم",
    degreeLabel: "الدرجة العلمية",
    degreeSelectHolder: "اختر الدرجة...",
    personalLinksTitle: "الروابط الشخصية",
    noLinksYet: "لا توجد روابط بعد — اضغط أعلاه لإضافة.",
    skillsAndExpTitle: "المهارات والخبرات",
    skillNameHolder: "اسم المهارة (مثال: React.js)",
    noSkillsYet: "لا توجد مهارات مضافة بعد.",
    expYearsLabel: "سنوات الخبرة العملية",
    selectPlaceholder: "اختر...",
    invalidPhoneForCountry: "رقم الهاتف غير صالح لهذه الدولة",
    guestNotice: "أنت تستخدم التطبيق كضيف — بياناتك محفوظة بأمان على جهازك.",
    avatarUpdatedSuccess: "تم تحديث صورتك بنجاح",
    avatarProcessError: "تعذر معالجة الصورة",
    avatarReadError: "تعذر قراءة الصورة",
    avatarUploadError: "تعذر رفع الصورة",
    avatarSaveError: "تعذر حفظ الصورة",
    guestProfileBanner: "👋 أنت تستخدم التطبيق كضيف — سنضيف تسجيل الدخول قريبًا لحفظ بياناتك على السحابة.",
    guestUserLabel: "👤 ضيف",
    // Currency & Finance Hub
    currencyAndGoldHub: "مركز العملات والذهب",
    currencyHubDesc: "عملات عالمية ومحلية، الذهب، والعملات الرقمية في مكان واحد",
    lastUpdated: "آخر تحديث:",
    gold24kPrice: "سعر الذهب (24K)",
    fiatCurrencies: "العملات النقدية",
    priceVsUsd: "السعر مقابل USD",
    cryptoCurrencies: "العملات الرقمية",
    livePrice: "السعر الحي",
    currencyDataSources: "مصادر البيانات: open.er-api.com للعملات و CoinGecko للذهب والعملات الرقمية — تحديث تلقائي كل دقيقة.",
    currencyConverter: "محول العملات",
    goldCalculator: "حاسبة الذهب",
    result: "النتيجة",
    weightInGrams: "الوزن (غ)",
    globalPrice: "السعر العالمي",
    localPrice: "السعر المحلي",
    localPriceFormula: "السعر المحلي = العالمي × سعر صرف {cur} الحي",
    // Economy News
    economyCurrenciesTab: "العملات",
    economyNewsTab: "الأخبار",
    dollarAlertTitle: "تنبيه: ارتفاع الدولار قد يزيد تكلفة منحك الدراسية",
    dollarAlertDesc: "راقب أسعار الصرف قبل تحويل رسوم التقديم أو دفع رسوم الجامعة.",
    howThisAffectsScholarships: "كيف يؤثر هذا على منحك؟",
    dollarIncreaseBullet: "• ارتفاع الدولار = زيادة تكلفة الدراسة بالخارج والرسوم بالعملة الأجنبية.",
    currencyDropBullet: "• انخفاض عملة بلدك = فرصة أفضل للمنح الممولة بالكامل بالدولار أو اليورو.",
    useCalculatorBullet: "• راقب أسعار الصرف الحية لتقدير النفقات الشهرية وتكاليف المعيشة بدقة.",
    // Jobs
    jobsTitle: "فرص العمل",
    jobsSubtitle: "فريلانسر، عن بُعد، ووظائف موثوقة.",
    jobsSearchPlaceholder: "ابحث عن فرصة، شركة، أو مهارة...",
    searchByMyCountry: "ابحث حسب بلدي: {country}",
    countryJobsOnlyHint: "يعرض فقط الفرص المتاحة في بلدك",
    featuredJobs: "فرص مميزة",
    recentJobs: "فرص حديثة",
    noMatchingJobs: "لا توجد فرص مطابقة حالياً — جرّب تعديل الفلتر.",
    perHour: "ساعة",
    perMonth: "شهر",
    perProject: "مشروع",
    newBadge: "جديد",
    jobAddedFavorite: "تمت الإضافة إلى المفضلة",
    jobRemovedFavorite: "تمت الإزالة من المفضلة",
    jobShareSubject: "وجدت هذه الفرصة في تطبيق الفرص: {title} لدى {company}.",
    freelance: "فريلانسر",
    remote: "عن بُعد",
    fullTime: "دوام كامل",
    jobCategoryAll: "الكل",
    jobCategoryProgramming: "برمجة",
    jobCategoryDesign: "تصميم",
    jobCategoryWriting: "كتابة",
    jobCategoryTeaching: "تدريس",
    jobCategoryTrades: "مهني",
    jobCategoryContent: "محتوى",
    jobCategoryEntry: "مبتدئ",
    jobCategoryNew: "جديد",
    jobDetails: "تفاصيل الفرصة",
    applyNow: "التقديم الآن",
    requirements: "المتطلبات",
    skills: "المهارات",
    registrationSteps: "خطوات التسجيل والبدء",
    paymentMethods: "طرق الدفع وسحب الأرباح",
    successStories: "قصص نجاح",
    pros: "المميزات",
    cons: "التحديات",
    averageSalary: "المتوسط",
    commission: "العمولة",
    minWithdrawal: "الحد الأدنى للسحب",
    processingTime: "وقت المعالجة",
    trustLevel: "مستوى الموثوقية",
    estimatedTime: "الوقت المقدر",
    // Sudan Universities Quick Banner
    sudanUniversitiesTitle: "دليل الجامعات السودانية",
    sudanUniversitiesSub: "16 جامعة · نسب القبول · تخصصات · تكاليف",
    jobOpportunitiesTitle: "فرص العمل",
    jobOpportunitiesSub: "50+ موقع · فريلانسر · وظائف · تدريس أونلاين",
    discover: "اكتشف",
    scholarshipsSwipe: "سحب",
    scholarshipsList: "قائمة",
    opportunityResults: "فرصة",
    resultsCount: "نتيجة",
    // Sudan Universities Guide Sheet
    sudanUniGuideTitle: "دليل الجامعات السودانية",
    sudanUniGuideSub: "{n} جامعة — مرتبة حسب متطلبات القبول",
    sudanUniMatchingTitle: "مطابقة ذكية بالنسبة",
    sudanUniMatchingSub: "اكتب نسبتك لنعرض الجامعات المؤهلة لك",
    sudanUniPctPlaceholder: "مثال: 82.5",
    sudanUniOnlyEligible: "المؤهلة فقط",
    sudanUniEligibleResult: "بنسبة {pct}% أنت مؤهل لـ {count} من {total} جامعة",
    sudanUniSearchPlaceholder: "ابحث بالجامعة أو التخصص...",
    sudanUniAllCities: "كل المدن",
    sudanUniAllFaculties: "كل التخصصات",
    sudanUniAllTypes: "كل الأنواع",
    sudanUniGov: "حكومية",
    sudanUniPrivate: "خاصة",
    sudanUniTechnical: "تقنية",
    sudanUniMinReq: "الحد الأدنى",
    sudanUniTuition: "الرسوم",
    sudanUniLiving: "السكن والمعيشة",
    sudanUniAdmissionDocs: "الوثائق والتقديم",
    sudanUniFacultiesList: "الكليات المتاحة",
    sudanUniVisitSite: "زيارة الموقع الرسمي",
    sudanUniEligibleBadge: "مؤهل للقبول ✓",
    sudanUniNotEligibleBadge: "دون الحد الأدنى",
    // AI Advisor & Apply Form & In-App Browser & Notifications & Onboarding
    aiAdvisorTitle: "مستشار الفرص الذكي",
    aiAdvisorConnected: "متصل — مدعوم بالذكاء الاصطناعي",
    aiAdvisorHint: "اسألني عن المنح والقبول! ✨",
    aiAdvisorClear: "مسح المحادثة",
    aiAdvisorPlaceholder: "اكتب سؤالك هنا...",
    aiAdvisorSend: "إرسال",
    applyInAppTitle: "التقديم داخل التطبيق",
    fullNameRequired: "الاسم الكامل *",
    fullNamePlaceholder: "اكتب اسمك الكامل",
    emailRequired: "البريد الإلكتروني *",
    phoneOptional: "رقم الهاتف",
    motivationLetterRequired: "رسالة الدوافع *",
    motivationPlaceholder: "لماذا تتقدم لهذه المنحة؟ ما هي أهدافك؟",
    fillAllRequiredFields: "الرجاء تعبئة جميع الحقول المطلوبة",
    saveApplicationFailed: "تعذر حفظ الطلب",
    applicationSubmittedSuccess: "تم إرسال طلبك بنجاح",
    officialWebsite: "الموقع الرسمي",
    openInBrowser: "فتح بالمتصفح",
    openingOfficialPage: "جاري فتح الصفحة الرسمية...",
    externalPolicyNote: "إذا لم تظهر الصفحة، فذلك بسبب سياسة أمان الموقع التي تفضل الفتح الخارجي.",
    openNow: "فتح الآن",
    officialSourceGuaranteed: "تطبيق الفرص يضمن لك الوصول إلى المصادر والبوابات الرسمية المعتمدة دائماً.",
    newWindow: "نافذة جديدة",
    markAllRead: "تعليم الكل كمقروء",
    noNotificationsYet: "لا توجد إشعارات حالياً",
    notificationsEmptyHint: "احفظ منحاً في «طلباتي» لتصلك تنبيهات المواعيد النهائية تلقائياً.",
    source: "المصدر",
    open: "فتح",
    onboarding1Title: "بطاقات المنح الذكية",
    onboarding1Desc: "اسحب لليمين لحفظ المنحة، ولليسار لتجاهلها. واجهة سريعة وجذابة تجعل اكتشاف الفرص متعة.",
    onboarding2Title: "أخبار العالم والمركز الاقتصادي",
    onboarding2Desc: "ابقَ على اطلاع بأحدث الأخبار العالمية والمحلية، الرياضة، الاقتصاد، ومؤشرات السوق في مكان واحد.",
    onboarding3Title: "ذكاء اصطناعي يربط الفرص",
    onboarding3Desc: "نحلل الأخبار العالمية ونربطها بفرص منح حقيقية تناسب تخصصك ومهاراتك تلقائياً.",
    skip: "تخطي",
    next: "التالي",
    getStarted: "ابدأ الآن",
    // Privacy & Security page
    privacySection: "الخصوصية والأمان",
    backToSettings: "العودة إلى الإعدادات",
    locationShare: "مشاركة الموقع الجغرافي",
    locationShareDesc: "يُستخدم لتحديد الدولة، العملة المحلية، والفرص القريبة منك.",
    hideProfile: "إخفاء بيانات الملف الشخصي",
    hideProfileDesc: "إخفاء معلوماتك عن مستخدمي التطبيق الآخرين.",
    twoFA: "المصادقة الثنائية (2FA)",
    twoFADesc: "طبقة حماية إضافية لحسابك.",
    setUp: "إعداد",
    twoFASoon: "ميزة المصادقة الثنائية ستتوفر قريباً.",
    locationDisabledToast: "تم إيقاف مشاركة الموقع. لن يتم استخدام GPS.",
    locationEnabledToast: "تم تفعيل مشاركة الموقع.",
    // About dialog
    aboutTitle: "حول التطبيق",
    aboutVisionLabel: "رؤيتنا",
    aboutVisionBody: "تمكين الشباب العربي من الوصول لأفضل الفرص التعليمية العالمية.",
    aboutTechLabel: "تقنيتنا",
    aboutTechBody: "فلترة ذكية ومطابقة دقيقة باستخدام الذكاء الاصطناعي.",
    aboutTrustLabel: "موثوقيتنا",
    aboutTrustBody: "جميع المصادر رسمية ومحدثة لحظياً.",
    contactUs: "تواصل معنا",
    aboutVersion: "الفُرَص — الإصدار 1.0",
    // Landing
    landingTagline: "بوابتك الذهبية للفرص العالمية",
    landingHeadline: "اكتشف، تقدّم، وحقق طموحك الأكاديمي",
    landingSubheadline: "منصة الفُرَص تجمع لك أفضل المنح الدراسية العربية والعالمية، مع مطابقة ذكية تبني على ملفك الشخصي.",
    landingCtaPrimary: "ابدأ الآن مجاناً",
    landingCtaSecondary: "تسجيل الدخول",
    landingFeaturesTitle: "لماذا منصة الفُرَص؟",
    landingFeature1Title: "مطابقة ذكية",
    landingFeature1Body: "خوارزمية AI تربط مهاراتك بالفرص الأنسب فوراً.",
    landingFeature2Title: "مصادر موثوقة",
    landingFeature2Body: "جميع المنح من جهات رسمية ومحدثة لحظياً.",
    landingFeature3Title: "تجربة فاخرة",
    landingFeature3Body: "تصميم زجاجي عصري بهوية ذهبية أنيقة.",
    landingWhyTitle: "رسالتنا ورؤيتنا",
    landingWhy1Title: "طموح بلا حدود",
    landingWhy1Body: "رؤيتنا هي تمكين كل طالب عربي من الوصول لأرقى الجامعات العالمية.",
    landingWhy2Title: "مطابقة ذكية",
    landingWhy2Body: "نستخدم تقنيات متطورة لربط ملفك الشخصي بالمنحة المثالية لك.",
    landingWhy3Title: "مصادر موثوقة",
    landingWhy3Body: "نضمن لك الوصول إلى بيانات دقيقة ومحدثة من الجهات الرسمية مباشرة.",
    landingContactSupport: "تواصل مع فريق الدعم",
    landingScholarshipsTitle: "أحدث المنح",
    landingScholarshipsSubtitle: "نظرة سريعة على فرص متاحة الآن",
    landingViewAll: "استعرض جميع المنح",
    landingFooter: "© 2026 الفُرَص — جميع الحقوق محفوظة",
  },
  en: {
    settings: "Settings",
    darkMode: "Dark mode",
    accountSettings: "Account settings",
    privacy: "Privacy & Security",
    about: "About",
    clearCache: "Clear cache",
    shareApp: "Share app",
    logout: "Sign out",
    language: "Language",
    arabic: "العربية",
    english: "English",
    notifications: "Notifications",
    confirmLogout: "Confirm sign out",
    confirmLogoutDesc: "Are you sure you want to sign out?",
    yesLogout: "Yes, sign out",
    cancel: "Cancel",
    privacyTitle: "Privacy & Security Policy",
    privacyBody:
      "We are committed to protecting your personal data. We never share your information with third parties without consent. Sensitive data is stored encrypted, and your email is used only for sign-in and notifications. You can delete your account and data at any time from account settings.",
    close: "Close",
    // Tabs
    tabScholarships: "Scholarships",
    tabNews: "News & Economy",
    tabCurrency: "Currency",
    tabApplications: "My Applications",
    tabProfile: "Profile",
    tabJobs: "Jobs",
    tabArabUnis: "Arab Unis",
    // Arab universities
    arabUniTitle: "Arab Universities Guide",
    arabUniSubtitle: "30+ universities across 20 Arab countries with admission requirements and scholarships.",
    arabUniSearch: "Search by university, country or city...",
    arabUniMatchTitle: "Smart match by your percentage",
    arabUniPctPlaceholder: "Your %",
    arabUniEligibleOnly: "Eligible only",
    arabUniEligibleCount: "You qualify for {n} universities based on your percentage.",
    arabUniAllCountries: "All countries",
    arabUniAllFaculties: "All faculties",
    arabUniResults: "{n} results",
    arabUniGov: "Public",
    arabUniPrivate: "Private",
    arabUniHasScholarships: "Scholarships",
    arabUniMin: "Minimum",
    arabUniEmpty: "No universities match your search.",
    arabUniCity: "City",
    arabUniType: "Type",
    arabUniLanguage: "Language of study",
    arabUniFaculties: "Faculties & majors",
    arabUniVisit: "Visit official website",
    arabUniCountriesTitle: "Choose a country",
    arabUniYourCountry: "Your country",
    arabUniUnisCount: "{n} universities",
    arabUniBack: "Back to countries",
    arabUniCompare: "Compare",
    arabUniCompareHint: "Pick up to 3 universities to compare",
    arabUniCompareOpen: "Show comparison ({n})",
    arabUniClear: "Clear selection",
    arabUniTuition: "Tuition fees",
    arabUniLiving: "Living cost",
    arabUniSeasons: "Application windows",
    arabUniDocs: "Required documents",
    arabUniSteps: "Application steps",
    arabUniMap: "View on map",
    arabUniOverview: "Overview",
    arabUniCosts: "Costs",
    arabUniAdmission: "Admission",
    // Notifications
    notifMatchTitle: "New smart match",
    notifMatchBody: "We found 3 scholarships matching your skills based on the latest global news.",
    notifDeadlineTitle: "Deadline approaching",
    notifDeadlineBody: "Chevening scholarship closes in 14 days. Don't miss it.",
    notifNewsTitle: "News linked to an opportunity",
    notifNewsBody: "The EU expanded Erasmus programs — check the new opportunities.",
    timeMinutesAgo: "minutes ago",
    timeHourAgo: "an hour ago",
    time3HoursAgo: "3 hours ago",
    notifFooter: "Notifications connect global news to opportunities matching your profile.",
    // Scholarships
    scholarshipsHint: "Opportunities aggregated from official global and Arab sources, sorted by your location and interests.",
    aiMatchBadge: "New smart match",
    aiMatchBody: "We found 3 scholarships matching your skills based on the latest global news.",
    swipeHint: "Swipe right to save • left to dismiss",
    noMoreScholarships: "No more scholarships",
    noMoreScholarshipsDesc: "We'll notify you when new ones become available",
    reload: "Reload",
    filterArabScholarships: "Arab Scholarships",
    filterGlobalScholarships: "Global Scholarships",
    studyLanguage: "Study language",
    langArabic: "Arabic",
    langEnglish: "English",
    langBoth: "Arabic/English",
    noScholarshipsCategory: "No scholarships in this category right now",
    verified: "Verified",
    manualReview: "Manual review",
    matchPercent: "Match",
    country: "Country",
    amount: "Amount",
    deadline: "Deadline",
    level: "Level",
    applyOfficial: "Apply on official website",
    applyOfficialNote: "The official website will open inside the app for you to apply directly.",
    sourceLink: "Source link",
    saved: "Scholarship saved to your applications",
    dismissed: "Scholarship dismissed",
    // News
    dataSaver: "Data saver (text only)",
    catAll: "All",
    catLocal: "Local",
    catArab: "Arab",
    catGlobal: "Global",
    lastUpdated: "Updated",
    loadingShort: "Loading...",
    newsCount: "stories",
    openSource: "Open source",
    // Weather
    searchCityPlaceholder: "Search weather for another city...",
    search: "Search",
    cityNotFound: "City not found",
    weatherFailed: "Couldn't update weather",
    loadingWeather: "Loading weather...",
    // Currency Calculator
    liveGoldCurrency: "Live currency & gold calculator",
    calc: "Calc",
    currency: "Currency",
    gold: "Gold",
    from: "From",
    to: "To",
    weight: "Weight (g)",
    karat: "Karat",
    estValue: "Estimated value",
    fetchingRates: "Fetching latest rates...",
    liveRatesAt: "Live rates — updated",
    fetchingGold: "Fetching gold price...",
    liveGoldAt: "Live gold price — updated",
    // Applications
    loading: "Loading...",
    noApps: "No applications yet",
    noAppsDesc: "Start by saving scholarships from the \"Scholarships\" tab",
    statusApplied: "Applied",
    statusSaved: "Saved",
    markApplied: "Mark as applied",
    markedApplied: "Marked as applied",
    updated: "Updated",
    removed: "Removed",
    // Profile
    fullName: "Full name",
    location: "Location",
    bio: "Bio",
    education: "Education",
    interests: "Core interests",
    skills: "Skills",
    addSkill: "Add a skill...",
    noSkills: "No skills added yet",
    save: "Save changes",
    saving: "Saving...",
    saveFailed: "Couldn't save",
    saved2: "Profile saved",
    edit: "Edit",
    editProfile: "Edit profile",
    editProfileDesc: "Update your details for better matches",
    profileCompletion: "Profile completion",
    completeProfileHint: "Complete your details for sharper scholarship matches.",
    personalInfo: "Personal info",
    interestsHint: "Used to match you with the most relevant opportunities.",
    yourNameHolder: "Type your name",
    locationHolder: "City, country",
    bioHolder: "Introduce yourself...",
    eduHolder: "e.g. BSc Computer Engineering, KSU, 2024",
    eduLabel: "Qualification",
    idCard: "FORAS · ID CARD",
    yourFullName: "Your full name",
    eduDetailsTitle: "Educational details",
    highSchoolLabel: "High school",
    highSchoolHolder: "High school name...",
    universityLabel: "University / College",
    universityHolder: "University or college name...",
    majorLabel: "Major / Field of study",
    majorHolder: "Major...",
    gpaLabel: "GPA",
    gpaScaleLabel: "Scale",
    degreeLabel: "Degree",
    degreeSelectHolder: "Select degree...",
    personalLinksTitle: "Personal links",
    noLinksYet: "No links yet — click above to add.",
    skillsAndExpTitle: "Skills & Experience",
    skillNameHolder: "Skill name (e.g. React.js)",
    noSkillsYet: "No skills added yet.",
    expYearsLabel: "Years of experience",
    selectPlaceholder: "Select...",
    invalidPhoneForCountry: "Invalid phone number for this country",
    guestNotice: "You are using the app as a guest — your data is securely stored on your device.",
    avatarUpdatedSuccess: "Your profile photo has been updated",
    avatarProcessError: "Unable to process image",
    avatarReadError: "Unable to read image",
    avatarUploadError: "Unable to upload image",
    avatarSaveError: "Unable to save image",
    guestProfileBanner: "👋 You are using the app as a guest — cloud sync will be available soon.",
    guestUserLabel: "👤 Guest",
    // Currency & Finance Hub
    currencyAndGoldHub: "Currency & Gold Hub",
    currencyHubDesc: "Global and local currencies, gold, and crypto all in one place",
    lastUpdated: "Last updated:",
    gold24kPrice: "Gold Price (24K)",
    fiatCurrencies: "Fiat Currencies",
    priceVsUsd: "Price vs USD",
    cryptoCurrencies: "Cryptocurrencies",
    livePrice: "Live Price",
    currencyDataSources: "Data sources: open.er-api.com for currencies & CoinGecko for gold and crypto — auto-updates every minute.",
    currencyConverter: "Currency Converter",
    goldCalculator: "Gold Calculator",
    result: "Result",
    weightInGrams: "Weight (g)",
    globalPrice: "Global Price",
    localPrice: "Local Price",
    localPriceFormula: "Local Price = Global × live {cur} exchange rate",
    // Economy News
    economyCurrenciesTab: "Currencies",
    economyNewsTab: "News",
    dollarAlertTitle: "Alert: Rising USD may increase study costs abroad",
    dollarAlertDesc: "Monitor exchange rates before transferring application fees or tuition.",
    howThisAffectsScholarships: "How does this affect your opportunities?",
    dollarIncreaseBullet: "• Stronger USD = Higher tuition and living expenses in foreign currency.",
    currencyDropBullet: "• Local currency decline = Better value for fully funded USD/EUR scholarships.",
    useCalculatorBullet: "• Monitor live exchange rates to estimate monthly expenses and living costs accurately.",
    // Jobs
    jobsTitle: "Job Opportunities",
    jobsSubtitle: "Freelance, remote, and verified trusted opportunities.",
    jobsSearchPlaceholder: "Search for opportunity, company, or skill...",
    searchByMyCountry: "Filter by my country: {country}",
    countryJobsOnlyHint: "Only displays opportunities available in your country",
    featuredJobs: "Featured Opportunities",
    recentJobs: "Recent Opportunities",
    noMatchingJobs: "No matching opportunities found — try modifying your filter.",
    perHour: "hour",
    perMonth: "month",
    perProject: "project",
    newBadge: "New",
    jobAddedFavorite: "Added to favorites",
    jobRemovedFavorite: "Removed from favorites",
    jobShareSubject: "I found this opportunity on Al-Foras: {title} at {company}.",
    freelance: "Freelance",
    remote: "Remote",
    fullTime: "Full Time",
    jobCategoryAll: "All",
    jobCategoryProgramming: "Programming",
    jobCategoryDesign: "Design",
    jobCategoryWriting: "Writing",
    jobCategoryTeaching: "Teaching",
    jobCategoryTrades: "Vocational",
    jobCategoryContent: "Content",
    jobCategoryEntry: "Entry-level",
    jobCategoryNew: "New",
    jobDetails: "Opportunity Details",
    applyNow: "Apply Now",
    requirements: "Requirements",
    skills: "Skills",
    registrationSteps: "Registration & Getting Started",
    paymentMethods: "Payout & Withdrawal Methods",
    successStories: "Success Stories",
    pros: "Advantages",
    cons: "Challenges",
    averageSalary: "Average",
    commission: "Commission",
    minWithdrawal: "Min Withdrawal",
    processingTime: "Processing Time",
    trustLevel: "Trust Level",
    estimatedTime: "Estimated Time",
    // Sudan Universities Quick Banner
    sudanUniversitiesTitle: "Sudan Universities Guide",
    sudanUniversitiesSub: "16 universities · admission rates · majors · costs",
    jobOpportunitiesTitle: "Job Opportunities",
    jobOpportunitiesSub: "50+ platforms · freelance · remote · tutoring",
    discover: "Discover",
    scholarshipsSwipe: "Swipe",
    scholarshipsList: "List",
    opportunityResults: "opportunities",
    resultsCount: "results",
    // Sudan Universities Guide Sheet
    sudanUniGuideTitle: "Sudan Universities Guide",
    sudanUniGuideSub: "{n} universities — sorted by admission requirements",
    sudanUniMatchingTitle: "Smart Percentage Match",
    sudanUniMatchingSub: "Enter your percentage to find eligible universities",
    sudanUniPctPlaceholder: "e.g. 82.5",
    sudanUniOnlyEligible: "Eligible only",
    sudanUniEligibleResult: "With {pct}%, you qualify for {count} of {total} universities",
    sudanUniSearchPlaceholder: "Search by university or major...",
    sudanUniAllCities: "All cities",
    sudanUniAllFaculties: "All majors",
    sudanUniAllTypes: "All types",
    sudanUniGov: "Public",
    sudanUniPrivate: "Private",
    sudanUniTechnical: "Technical",
    sudanUniMinReq: "Min Requirement",
    sudanUniTuition: "Tuition Fees",
    sudanUniLiving: "Housing & Living",
    sudanUniAdmissionDocs: "Documents & Admission",
    sudanUniFacultiesList: "Available Faculties",
    sudanUniVisitSite: "Visit Official Website",
    sudanUniEligibleBadge: "Eligible ✓",
    sudanUniNotEligibleBadge: "Below Minimum",
    // AI Advisor & Apply Form & In-App Browser & Notifications & Onboarding
    aiAdvisorTitle: "Smart Opportunity Advisor",
    aiAdvisorConnected: "Online — Powered by AI",
    aiAdvisorHint: "Ask me about scholarships and admissions! ✨",
    aiAdvisorClear: "Clear Chat",
    aiAdvisorPlaceholder: "Type your question here...",
    aiAdvisorSend: "Send",
    applyInAppTitle: "In-App Application",
    fullNameRequired: "Full Name *",
    fullNamePlaceholder: "Enter your full name",
    emailRequired: "Email Address *",
    phoneOptional: "Phone Number",
    motivationLetterRequired: "Motivation Letter *",
    motivationPlaceholder: "Why are you applying for this scholarship? What are your goals?",
    fillAllRequiredFields: "Please fill in all required fields",
    saveApplicationFailed: "Unable to save application",
    applicationSubmittedSuccess: "Your application was submitted successfully",
    officialWebsite: "Official Website",
    openInBrowser: "Open in Browser",
    openingOfficialPage: "Opening official page...",
    externalPolicyNote: "If the page does not appear, the website security policy requires opening in external browser.",
    openNow: "Open Now",
    officialSourceGuaranteed: "Al-Foras guarantees access to verified official portals and sources.",
    newWindow: "New Window",
    markAllRead: "Mark all as read",
    noNotificationsYet: "No notifications right now",
    notificationsEmptyHint: "Save scholarships to «My Applications» to receive deadline reminders automatically.",
    source: "Source",
    open: "Open",
    onboarding1Title: "Smart Scholarship Cards",
    onboarding1Desc: "Swipe right to save, swipe left to dismiss. Fast and engaging way to discover opportunities.",
    onboarding2Title: "Global News & Economy Hub",
    onboarding2Desc: "Stay informed with real-time world and local news, sports, economy, and financial indicators.",
    onboarding3Title: "AI That Connects Opportunities",
    onboarding3Desc: "We analyze global news and connect them with real scholarships matching your profile automatically.",
    skip: "Skip",
    next: "Next",
    getStarted: "Get Started",
    // Privacy & Security page
    privacySection: "Privacy & Security",
    backToSettings: "Back to settings",
    locationShare: "Share location",
    locationShareDesc: "Used for country detection, local currency, and nearby opportunities.",
    hideProfile: "Hide profile details",
    hideProfileDesc: "Hide your details from other app users.",
    twoFA: "Two-factor authentication (2FA)",
    twoFADesc: "Extra protection for your account.",
    setUp: "Set up",
    twoFASoon: "Two-factor authentication will be available soon.",
    locationDisabledToast: "Location sharing turned off. GPS will not be used.",
    locationEnabledToast: "Location sharing enabled.",
    // About dialog
    aboutTitle: "About Al-Foras",
    aboutVisionLabel: "Our Vision",
    aboutVisionBody: "Empowering Arab youth to reach the world's best educational opportunities.",
    aboutTechLabel: "Our Technology",
    aboutTechBody: "Smart filtering and precise AI-powered matching.",
    aboutTrustLabel: "Our Trust",
    aboutTrustBody: "All sources are official and updated in real time.",
    contactUs: "Contact Us",
    aboutVersion: "Al-Foras — Version 1.0",
    // Landing
    landingTagline: "Your golden gateway to global opportunities",
    landingHeadline: "Discover, apply, and achieve your academic dream",
    landingSubheadline: "Al-Foras curates the best Arab and global scholarships with AI-powered matching tailored to your profile.",
    landingCtaPrimary: "Get Started — It's Free",
    landingCtaSecondary: "Sign In",
    landingFeaturesTitle: "Why Al-Foras Platform?",
    landingFeature1Title: "Smart Matching",
    landingFeature1Body: "AI algorithm connects your skills to the best-fit opportunities instantly.",
    landingFeature2Title: "Trusted Sources",
    landingFeature2Body: "Every scholarship is from an official, real-time updated source.",
    landingFeature3Title: "Premium Experience",
    landingFeature3Body: "Modern glassmorphism design with an elegant gold identity.",
    landingWhyTitle: "Our Mission & Vision",
    landingWhy1Title: "Limitless Ambition",
    landingWhy1Body: "Our vision is to empower every Arab student to reach the world's top universities.",
    landingWhy2Title: "Smart Matching",
    landingWhy2Body: "Advanced technology connects your profile to the scholarship that fits you best.",
    landingWhy3Title: "Trusted Sources",
    landingWhy3Body: "We guarantee access to accurate, real-time data straight from official authorities.",
    landingContactSupport: "Contact Support Team",
    landingScholarshipsTitle: "Latest Scholarships",
    landingScholarshipsSubtitle: "A quick look at opportunities available now",
    landingViewAll: "Browse all scholarships",
    landingFooter: "© 2026 Al-Foras — All rights reserved",
  },
};

const ARABIC_COUNTRY_CODES = new Set(
  ["SA","AE","QA","KW","BH","OM","EG","SD","MA","DZ","TN","LY","JO","LB","SY","IQ","YE","PS","KM","MR","SO","DJ"]
);

const detectInitialLang = (): Lang => {
  // If user has explicitly and manually switched language in settings/navbar, respect it
  if (localStorage.getItem("foras-lang-manual") === "true") {
    const stored = localStorage.getItem("foras-lang") as Lang | null;
    if (stored === "ar" || stored === "en") return stored;
  }

  // 1. Check Country Code from previous geo-sync
  const cc = localStorage.getItem("foras-countrycode");
  if (cc && ARABIC_COUNTRY_CODES.has(cc.toUpperCase())) return "ar";

  // 2. Check Browser Languages (device preferences array)
  try {
    const langs = (navigator.languages && navigator.languages.length > 0)
      ? navigator.languages
      : [navigator.language || "ar"];
    const hasArabic = langs.some((l) => l && l.toLowerCase().startsWith("ar"));
    if (hasArabic) return "ar";

    // If English is explicitly the first preference
    const primary = (langs[0] || "").toLowerCase();
    if (primary.startsWith("en")) return "en";
    if (primary.startsWith("ar")) return "ar";
  } catch {}

  // 3. Check Device Timezone (Arab region timezones default to Arabic)
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone.toLowerCase();
    if (
      tz.includes("khartoum") || tz.includes("cairo") || tz.includes("riyadh") ||
      tz.includes("dubai") || tz.includes("amman") || tz.includes("baghdad") ||
      tz.includes("beirut") || tz.includes("damascus") || tz.includes("kuwait") ||
      tz.includes("qatar") || tz.includes("bahrain") || tz.includes("muscat") ||
      tz.includes("casablanca") || tz.includes("algiers") || tz.includes("tunis") ||
      tz.includes("tripoli") || tz.includes("gaza") || tz.includes("jerusalem") ||
      tz.includes("sanaa") || tz.includes("aden") || tz.includes("sudan")
    ) {
      return "ar";
    }
  } catch {}

  // Fallback to device language or Arabic default
  const browser = (navigator.language || "ar").toLowerCase();
  return browser.startsWith("en") ? "en" : "ar";
};

const Ctx = createContext<LanguageCtx>({
  lang: "ar", dir: "rtl",
  setLang: () => {}, toggleLang: () => {},
  t: (k) => k,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() => detectInitialLang());
  const dir: "rtl" | "ltr" = lang === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = dir;
    localStorage.setItem("foras-lang", lang);
  }, [lang, dir]);

  // If country code becomes known later and user hasn't manually picked, refine.
  useEffect(() => {
    const onCountry = (e: Event) => {
      if (localStorage.getItem("foras-lang-manual")) return;
      const code = (e as CustomEvent).detail?.code as string | undefined;
      if (!code) return;
      setLangState(ARABIC_COUNTRY_CODES.has(code.toUpperCase()) ? "ar" : "en");
    };
    window.addEventListener("foras:countrychange", onCountry as EventListener);
    return () => window.removeEventListener("foras:countrychange", onCountry as EventListener);
  }, []);

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    localStorage.setItem("foras-lang-manual", "true");
  }, []);
  const toggleLang = useCallback(() => setLang(lang === "ar" ? "en" : "ar"), [lang, setLang]);
  const t = useCallback((key: string) => STRINGS[lang][key] ?? key, [lang]);

  // touch COUNTRIES so tree-shaker keeps the import side-effect-free
  void COUNTRIES;

  return (
    <Ctx.Provider value={{ lang, dir, setLang, toggleLang, t }}>{children}</Ctx.Provider>
  );
};

export const useLanguage = () => useContext(Ctx);
