import { createContext, useContext, useEffect, useState, ReactNode, useCallback } from "react";
import { COUNTRIES } from "@/lib/countries";

export type Lang = "ar" | "en";

interface LanguageCtx {
  lang: Lang;
  language: Lang;
  dir: "rtl" | "ltr";
  isRtl: boolean;
  setLang: (l: Lang) => void;
  toggleLang: () => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const STRINGS: Record<Lang, Record<string, string>> = {
  ar: {
    settings: "الإعدادات",
    darkMode: "الوضع الليلي",
    accountSettings: "إعدادات الحساب",
    privacy: "الخصوصية والأمان",
    about: "حول التطبيق",
    clearCache: "مسح الملفات المؤقتة",
    shareApp: "مشاركة التطبيق",
    logout: "تسجيل الخروج",
    language: "اللغة",
    arabic: "العربية",
    english: "English",
    notifications: "الإشعارات",
    confirmLogout: "تأكيد تسجيل الخروج",
    confirmLogoutDesc: "هل أنت متأكد أنك تريد الخروج من حسابك؟",
    yesLogout: "نعم، اخرج",
    cancel: "إلغاء",
    privacyTitle: "سياسة الخصوصية والأمان",
    privacyBody:
      "نحن نلتزم بحماية بياناتك الشخصية. لا نشارك معلوماتك مع أطراف ثالثة دون إذنك. تُخزّن البيانات الحساسة بشكل مشفّر، ويُستخدم بريدك الإلكتروني فقط لتسجيل الدخول والإشعارات. يمكنك حذف حسابك وبياناتك في أي وقت من إعدادات الحساب.",
    settingsPreferencesGroup: "التفضيلات والمظهر",
    settingsAccountGroup: "الحساب والأمان",
    settingsDataGroup: "البيانات والذاكرة",
    settingsAboutGroup: "حول التطبيق والدعم",
    settingsCurrency: "العملة المحلية",
    settingsCurrencyDesc: "عرض الأسعار والمبالغ بعملتك المفضلة",
    settingsLanguageDesc: "تغيير لغة الواجهة بين العربية والإنجليزية",
    settingsDarkDesc: "السمة الليلية الذهبية الفاخرة مفعلة افتراضياً",
    settingsTextOnly: "وضع توفير البيانات",
    settingsTextOnlyDesc: "تقليل استهلاك الإنترنت وتسريع التصفح",
    settingsAccountDesc: "إدارة بيانات الحساب والملف التعريفي",
    settingsPrivacyDesc: "أذونات الموقع والظهور والأمان",
    settingsAdminDesc: "تحديث المنح، الوظائف، والجامعات",
    settingsCacheDesc: "تحرير مساحة التخزين المؤقت في جهازك",
    settingsShareDesc: "شارك منصة الفرص مع أصدقائك",
    settingsAboutDesc: "الرؤية، الإصدار، ومعلومات التواصل",
    settingsGuestAccount: "حساب مستخدم",
    settingsActiveBadge: "نشط",
    settingsSelectCurrency: "اختر العملة المفضلة",
    settingsPersona: "نوع وهوية الحساب",
    settingsPersonaDesc: "تخصيص الحقول المعروضة للطلاب والباحثين عن منح أو المهنيين والموظفين",
    settingsPersonaStudent: "طالب وباحث عن منح",
    settingsPersonaStudentDesc: "إبراز المؤهلات الأكاديمية، الجامعة، والتخصص",
    settingsPersonaPro: "مهني ومستقل وموظف",
    settingsPersonaProDesc: "إبراز سنوات الخبرة، المهارات المتقدمة، وروابط الأعمال",
    close: "إغلاق",
    // Tabs
    tabScholarships: "المنح والفرص",
    tabNews: "الأخبار والاقتصاد",
    tabCurrency: "العملات",
    tabApplications: "طلباتي",
    tabProfile: "الملف الشخصي",
    tabJobs: "فرص العمل",
    tabArabUnis: "الجامعات العربية والعالمية",
    // Arab and Global universities
    arabUniTitle: "دليل الجامعات العربية والعالمية",
    arabUniSubtitle: "أدلة شاملة للجامعات والمنح الحكومية المعتمدة في 8 دول عربية وكبرى الدول المانحة عالمياً.",
    academicHubTabArab: "ركن الجامعات العربية",
    academicHubTabGlobal: "ركن الجامعات العالمية",
    arabUnisSubTab: "الجامعات العربية",
    globalUnisSubTab: "الجامعات العالمية",
    quickUnisGuideTitle: "دليل الجامعات",
    globalUnisHeading: "بوابات الدول العالمية والمنح الدولية",
    globalUnisSubheading: "دليل استقصائي لكبرى الدول المانحة مع مواعيد التقديم السنوية وشروط القبول والروابط الرسمية.",
    globalGuaranteedTier: "منح سنوية مضمونة وممولة بالكامل",
    globalPeriodicTier: "منح دورية ونخبوية وتنافسية",
    globalApplicationWindow: "نافذة التقديم السنوية",
    globalFundingType: "نوع التمويل والتغطية",
    globalLanguages: "لغات الدراسة",
    globalDegrees: "المراحل المتاحة",
    globalPortals: "البوابات الرسمية",
    globalTopUnis: "أبرز الجامعات المعتمدة عالمياً",
    globalCoverageList: "المزايا والتغطية المالية",
    arabUniSearch: "ابحث باسم الجامعة أو الدولة أو المدينة...",
    arabUniMatchTitle: "المطابقة الذكية بنسبتك",
    arabUniPctPlaceholder: "نسبتك %",
    arabUniEligibleOnly: "المؤهلة فقط",
    arabUniEligibleCount: "أنت مؤهل لـ {n} جامعة حسب نسبتك.",
    arabUniAllCountries: "كل الدول",
    arabUniAllFaculties: "كل الكليات",
    arabUniResults: "{n} نتيجة",
    arabUniGov: "حكومية",
    arabUniPrivate: "خاصة",
    arabUniHasScholarships: "منح متاحة",
    arabUniMin: "الحد الأدنى",
    arabUniEmpty: "لا توجد جامعات مطابقة لبحثك.",
    arabUniCity: "المدينة",
    arabUniType: "النوع",
    arabUniLanguage: "لغة الدراسة",
    arabUniFaculties: "الكليات والتخصصات",
    arabUniVisit: "الموقع الرسمي",
    arabUniCountriesTitle: "اختر الدولة",
    arabUniYourCountry: "دولتك",
    arabUniUnisCount: "{n} جامعة",
    arabUniBack: "رجوع للدول",
    arabUniCompare: "مقارنة",
    arabUniCompareHint: "اختر حتى 3 جامعات للمقارنة",
    arabUniCompareOpen: "عرض المقارنة ({n})",
    arabUniClear: "إلغاء التحديد",
    arabUniTuition: "الرسوم الدراسية",
    arabUniLiving: "تكلفة المعيشة",
    arabUniSeasons: "مواعيد التقديم",
    arabUniDocs: "المستندات المطلوبة",
    arabUniSteps: "خطوات التقديم",
    arabUniMap: "الخريطة",
    arabUniOverview: "نظرة عامة",
    arabUniCosts: "التكاليف",
    arabUniAdmission: "القبول",
    arabUniSmartMatchDesc: "اكتب معدلك أو نسبتك لنعرض الجامعات التي تقبلك وتطابق مؤهلاتك",
    arabUniSmartMatchQualified: "بنسبة {pct}% أنت مؤهل لـ {eligible} من {total} جامعة {scope}",
    arabUniAllScope: "عربية",
    arabUniInCountry: "في {country}",
    arabUniBackToCountries: "العودة إلى قائمة الدول",
    arabUniScholarshipsAvailable: "تتوفر منح معتمدة",
    arabUniInstitutionsCount: "يتضمن {count} جامعة ومؤسسة معتمدة · الحد الأدنى للقبول يبدأ من %{min}",
    arabUniOfficialPortalsBanner: "بوابات ومصادر رسمية معتمدة",
    arabUniScholarshipTypeLabel: "نوع المنح الدراسية:",
    arabUniOfficialPortalsLabel: "البوابات الرسمية للتقديم والاستعلام:",
    arabUniAllMajorsOption: "كل التخصصات والكليات",
    arabUniAllUnisOption: "كل الجامعات",
    arabUniGovOption: "حكومية",
    arabUniPrivOption: "خاصة",
    arabUniTechOption: "تقنية",
    arabUniClearFilters: "مسح الفلاتر",
    arabUniSelectedCompare: "تم تحديد {count} من 3",
    arabUniTuitionCoveredGov: "مشمولة بمنح حكومية ممولة بالكامل أو رسوم رمزية",
    arabUniLivingCoveredStipend: "مغطاة براتب شهري حكومي منتظم",
    arabUniMainCycle: "التقديم الرئيسي: {window} · التقديم التكميلي للفصول اللاحقة حسب تقويم الجامعة",
    arabUniAssociatedGovGrant: "المنحة الحكومية المعتمدة والتغطية",
    arabUniRequiredDocsTitle: "المستندات المطلوبة",
    arabUniApplicationStepsTitle: "خطوات التقديم",
    arabUniLocationMapBtn: "الخريطة",
    arabUniOfficialSiteBtn: "الموقع الرسمي",
    arabUniDirectScholarshipFilter: "منح مباشرة نشطة 🔥",
    arabUniAlumniFilter: "خريجون ورواد 🎓",
    arabUniPresenceFilter: "تواجد طلابي 👥",
    arabUniSearchPlaceholder: "ابحث باسم الجامعة، التخصص، المنحة، أو الرواد...",
    // Global Universities Tab Keys
    globalUniSelectCountry: "اختر الدولة العالمية",
    globalUniCountryCount: "{n} دولة",
    globalUniAllCountries: "كافة الدول المانحة",
    globalUniCategoryAll: "الكل",
    globalUniFilterAll: "جميع الصروح",
    globalUniFilterScholarships: "منح مباشرة نشطة 🔥",
    globalUniFilterAlumni: "خريجون ورواد 🎓",
    globalUniFilterPresence: "تواجد طلابي 👥",
    globalUniDirectGrantBadge: "منحة مباشرة نشطة 🔥",
    globalUniCategoryArabPopular: "الوجهات الأكثر طلباً للطلاب العرب",
    globalUniCategoryEuGrants: "منح الاتحاد الأوروبي والتمويل الكامل",
    globalUniCategoryAnglophone: "الدول الإنجليزية والآيفي ليغ",
    globalUniCategoryEurasiaEastAsia: "أوراسيا وشرق آسيا وجنوب أوروبا",
    globalUniCategoryAdvancedEurope: "أوروبا المتقدمة وأوقيانوسيا",
    globalUniGuaranteed: "منح سنوية مضمونة",
    globalUniPeriodic: "دورية / نخبوية",
    globalUniGuaranteedBadge: "سنوية مضمونة",
    globalUniAccreditedUnis: "جامعات معتمدة",
    globalUniScholarshipsAvailable: "منح متاحة",
    globalUniSearchPlaceholder: "ابحث عن اسم الجامعة، المدينة، أو التخصص في هذا البلد...",
    globalUniFoundUnis: "تم العثور على {count} جامعة معتمدة",
    globalUniBannerDesc: "يتضمن {count} جامعات عالمية مرموقة · {funding}",
    globalUniLeadingBadge: "عالمية رائدة",
    globalUniScholarshipEligible: "مشمولة بالمنحة الحكومية",
    globalUniFundingStatus: "حالة التمويل الأكاديمي",
    globalUniEligibleApply: "مؤهل للتقديم ✓",
    globalUniWebsite: "الموقع",
    globalUniFullDetails: "التفاصيل الكاملة",
    globalUniNoResults: "لا توجد جامعات مطابقة للبحث الحالي.",
    globalUniResetSearch: "إلغاء البحث للبدء من جديد",
    globalUniCityLabel: "المدينة",
    globalUniMinAdmissionLabel: "الحد الأدنى",
    globalUniInstTypeLabel: "النوع",
    globalUniInstTypeValue: "حكومية دولية معتمدة",
    globalUniLangLabel: "لغة الدراسة",
    globalUniTuitionLabel: "الرسوم الدراسية",
    globalUniTuitionCovered: "مشمولة بمنح حكومية ممولة بالكامل أو رسوم رمزية",
    globalUniLivingLabel: "تكلفة المعيشة",
    globalUniLivingCovered: "مغطاة براتب شهري حكومي منتظم",
    globalUniDeadlinesTitle: "مواعيد التقديم",
    globalUniDeadlinesDesc: "التقديم الرئيسي: {window} · التقديم التكميلي للفصول اللاحقة حسب تقويم الجامعة",
    globalUniAssociatedScholarshipTitle: "المنحة الحكومية المعتمدة المرتبطة بهذه الجامعة:",
    globalUniFacultiesTitle: "الكليات والتخصصات",
    globalUniDocsTitle: "المستندات المطلوبة",
    globalUniStepsTitle: "خطوات التقديم",
    globalUniLocationMap: "الخريطة",
    globalUniVisitOfficialSite: "الموقع الرسمي",
    // Admin Dashboard Keys
    adminTitle: "لوحة تحكم إدارة منصة الفُرَص",
    adminActiveSession: "الجلسة نشطة: {name} ({role})",
    adminActiveSessionLabel: "الجلسة نشطة:",
    adminSuperAdminRole: "المدير العام",
    adminModeratorRole: "مشرف محتوى",
    adminSignInPrompt: "سجّل الدخول للوصول إلى صلاحيات التحرير والإشراف",
    adminLoginPrompt: "سجل الدخول للمتابعة",
    adminLockLogout: "قفل وخروج",
    adminLoginTitle: "تسجيل دخول الإدارة والمشرفين",
    adminLoginSubtitle: "أدخل البريد الإلكتروني وكلمة المرور المشفرة للمتابعة",
    adminLoginDesc: "أدخل بيانات الاعتماد الرسمية للوصول إلى لوحة التحكم",
    adminIdentifierLabel: "البريد الإلكتروني أو اسم المستخدم",
    adminEmailOrUsername: "البريد الإلكتروني أو اسم المستخدم",
    adminPasswordLabel: "كلمة المرور / الرمز السريع",
    adminPasswordOrPin: "كلمة المرور / الرمز السريع",
    adminLoginSubmit: "دخول لوحة التحكم",
    adminUnlockBtn: "فتح لوحة التحكم",
    adminForgotPassword: "نسيت كلمة المرور؟",
    adminRecoveryTitle: "استعادة كلمة مرور الإدارة",
    adminRecoveryDesc: "سيتم إرسال كود تحقق أمني فوري إلى البريد الموحد الرسمي alforas.one@gmail.com",
    adminSendOtpBtn: "إرسال كود الاستعادة (OTP)",
    adminOtpSentMsg: "تم إرسال كود التحقق الأمني المكون من 6 أرقام إلى البريد الموحد الرسمي.",
    adminEnterOtpLabel: "أدخل كود التحقق الأمني (6 أرقام)",
    adminVerifyOtpBtn: "التحقق من الكود والمتابعة",
    adminNewPasswordLabel: "تعيين كلمة المرور الجديدة",
    adminConfirmNewPasswordLabel: "تأكيد كلمة المرور الجديدة",
    adminSaveNewPasswordBtn: "حفظ كلمة المرور الجديدة وفك الحظر",
    adminLockoutTitle: "🚨 تم حظر إمكانية تسجيل الدخول أمنياً",
    adminLockoutNotice: "تم تجاوز الحد الأقصى المسموح به (3 محاولات خاطئة). تم تسجيل كلمات السر المدخلة وتوثيق المحاولة في سجل التدقيق وإبلاغ الإدارة.",
    adminLockedNeedAdminUnlock: "لا يمكن تسجيل الدخول حالياً حتى يتم إلغاء الحظر من قبل المدير العام أو استعادة الحساب بكود OTP المعتمد.",
    adminAttemptsLeft: "متبقي لديك {count} محاولات قبل حظر الحساب",
    adminOneAttemptLeft: "تحذير: متبقي محاولة واحدة فقط قبل الحظر التام",
    adminSearchMenu: "بحث في عناصر القائمة...",
    adminSelectAll: "تحديد الكل",
    adminDeselectAll: "إلغاء تحديد الكل",
    adminSelectAllLabel: "تحديد الكل",
    adminAddScholarship: "إضافة منحة جديدة",
    adminAddScholarshipBtn: "إضافة منحة جديدة",
    adminAddJob: "إضافة وظيفة عمل حر",
    adminAddJobBtn: "إضافة وظيفة عمل حر",
    adminActiveScholarshipsCount: "المنح النشطة حالياً ({count} منحة)",
    adminRangeHint: "💡 يمكنك تحديد نطاق بالضغط على Shift + النقر",
    adminNoScholarships: "لا توجد منح دراسية في هذا القسم",
    adminNoScholarshipsDesc: "يمكنك إضافة منحة جديدة بالضغط على زر إضافة منحة أعلاه.",
    adminEdit: "تحرير",
    adminArchive: "أرشفة",
    adminActiveJobsCount: "فرص العمل الحر النشطة ({count} وظيفة)",
    adminNoJobs: "لا توجد فرص عمل حر مسجلة حالياً",
    adminVaultTitle: "سلة المحذوفات والأرشيف ({count} عنصر)",
    adminVaultHint: "تخزين آمن للمحذوفات مع إمكانية الاستعادة",
    adminVaultEmpty: "سلة المحذوفات فارغة تماماً",
    adminVaultEmptyDesc: "جميع العناصر المحذوفة تظهر هنا لحمايتها من الفقدان العرضي.",
    adminRestore: "استعادة",
    adminDeletePermanently: "حذف نهائي",
    adminDangerZone: "منطقة الخطر - تفريغ الأرشيف نهائياً",
    adminDangerZoneDesc: "سيؤدي هذا الإجراء إلى مسح كافة العناصر المؤرشفة نهائياً وبلا رجعة. يرجى توخي الحذر الشديد.",
    adminTypeDeleteConfirm: "اكتب DELETE أو تأكيد لإفراغ الأرشيف",
    adminEmptyVaultBtn: "تفريغ الأرشيف نهائياً",
    adminAiUrlExtractor: "مستخرج روابط المنح والوظائف الذكي بالذكاء الاصطناعي",
    adminAiUrlExtractorDesc: "ضع رابط أي منحة أو وظيفة عالمية، وسيقوم النظام الذكي بقراءة واستخراج كافة البيانات تلقائياً",
    adminExtractBtn: "استخراج ومعالجة البيانات",
    adminExtractedReady: "تم استخراج البيانات وجاهزة للمراجعة والنشر",
    adminApprovePublishNow: "اعتماد ونشر فوري",
    adminTeamTitle: "فريق الإدارة والمشرفين المعتمدين",
    adminTeamDesc: "التحكم في صلاحيات المشرفين والمحررين والقيود الأمنية",
    adminNoPermissionToast: "ليس لديك صلاحية لتنفيذ هذا الإجراء. يرجى التواصل مع المدير العام.",
    adminPermissionDenied: "تم رفض الإجراء لعدم وجود الصلاحية الكافية",
    adminCanEditLabel: "صلاحية التحرير والتعديل",
    adminCanDeleteLabel: "صلاحية الحذف والأرشفة",
    adminCanCreateLabel: "صلاحية إضافة عناصر جديدة",
    adminCanAutoPublishLabel: "نشر فوري دون مراجعة",
    adminPermissionsUpdatedToast: "تم تحديث صلاحيات المشرف بنجاح",
    adminAuditLogTitle: "سجل الأنشطة والتدقيق الأمني ({count} عملية)",
    adminPendingTitle: "طلبات المراجعة المعلقة ({count} طلب)",
    adminNoPending: "لا توجد طلبات مراجعة معلقة",
    adminApprovePublish: "موافقة ونشر",
    adminBackupTitle: "تصدير النسخة الاحتياطية للبيانات",
    adminBackupDesc: "قم بتحميل ملف JSON يحتوي على كافة المنح والوظائف وسجلات الأمان وسلة المحذوفات للاحتفاظ بنسخة محلية آمنة.",
    adminDownloadBackupBtn: "تحميل النسخة الاحتياطية كاملة (JSON)",
    adminItemsSelected: "تم تحديد {count} عنصر",
    adminClearSelection: "إلغاء التحديد",
    adminRestoreSelected: "استعادة المحدد ({count})",
    adminArchiveSelected: "أرشفة المحدد ({count})",
    adminDeleteModalTitle: "تأكيد أرشفة العنصر مع إشعار الإدارة",
    adminDeleteModalDesc: "بصفتك مشرفاً، ستتم أرشفة «{title}» وإرسال إشعار فوري للمدير العام.",
    adminCancel: "إلغاء",
    adminConfirmArchive: "تأكيد الأرشفة",
    adminEditScholarshipTitle: "إضافة / تحرير بيانات المنحة الشاملة",
    adminEditScholarshipSubtitle: "تخصيص تصنيف ونطاق المنحة (عربية / عالمية)، تفاصيل الدعم المالي، والربط بالجامعات",
    adminEditScholarshipDesc: "أدخل كافة بيانات ومعايير القبول والتغطية للمنحة الدراسية",
    adminScholarshipScopeLabel: "نطاق وتصنيف المنحة",
    adminScopeArabOption: "منحة عربية (إقليم الشرق الأوسط وشمال أفريقيا)",
    adminScopeGlobalOption: "منحة عالمية مانحة (الدول الأجنبية الكبرى)",
    adminScopeGeneralOption: "منحة دولية عامة",
    adminHostCountryLabel: "الدولة المستضيفة",
    adminSelectCountryPlaceholder: "-- اختر الدولة --",
    adminCustomCountryLabel: "أو اكتب الدولة يدوياً",
    adminInstitutionLabel: "اسم الجامعة أو الجهة المانحة (بالعربية)",
    adminInstitutionEnLabel: "اسم الجامعة أو الجهة المانحة (بالإنجليزية)",
    adminStudyLanguageLabel: "لغة التدريس والبرنامج",
    adminStudyLangAr: "العربية",
    adminStudyLangEn: "الإنجليزية",
    adminStudyLangBoth: "عربي / إنجليزي",
    adminScholarshipTitleAr: "عنوان المنحة (بالعربية)",
    adminScholarshipTitleEn: "عنوان المنحة (بالإنجليزية)",
    adminTitleAr: "عنوان المنحة (بالعربية)",
    adminTitleEn: "عنوان المنحة (بالإنجليزية)",
    adminCountryUniversity: "الدولة والجامعة المانحة",
    adminDegreeLevelLabel: "المرحلة الدراسية",
    adminDegreeLevel: "المرحلة الدراسية",
    adminFundingCoverageLabel: "نوع التمويل والدعم",
    adminFundingCoverage: "نوع التمويل والتغطية",
    adminDeadlineLabel: "الموعد النهائي للتقديم",
    adminDeadline: "الموعد النهائي للتقديم",
    adminApplyUrlLabel: "رابط التقديم الرسمي المباشر",
    adminApplyUrl: "رابط التقديم الرسمي المباشر",
    adminLangReqLabel: "متطلبات واختبارات اللغة (IELTS / TOEFL)",
    adminLanguageReq: "متطلبات واختبارات اللغة",
    adminDescLabel: "وصف ومزايا المنحة والتخصصات",
    adminDescriptionBenefits: "وصف ومزايا وتفاصيل المنحة",
    adminCustomFieldsSection: "حقول وشروط وملاحظات إضافية مخصصة",
    adminCustomFieldsTitle: "حقول وشروط وملاحظات مخصصة إضافية",
    adminAddFieldBtn: "إضافة حقل جديد",
    adminAddField: "إضافة حقل جديد",
    adminCancelBtn: "إلغاء",
    adminSavePublishBtn: "حفظ ونشر المنحة",
    adminSavePublish: "حفظ ونشر المنحة",
    adminSaveSuccessToast: "تم حفظ وتحديث بيانات المنحة بنجاح",
    adminArchiveConfirmTitle: "تأكيد أمني لنقل العنصر للأرشيف",
    adminArchiveConfirmPrompt: "أنت على وشك أرشفة هذا العنصر. سيتم نقله للأرشيف فوراً وإرسال إشعار رسمي للمدير العام.",
    adminConfirmArchiveBtn: "تأكيد الأرشفة والإشعار",
    adminEditJobTitle: "إضافة / تحرير فرصة عمل حر وعن بُعد",
    adminEditJobDesc: "تخصيص تفاصيل الدخل بالدولار ومتطلبات المهارات وطرق السحب",
    adminJobTitleAr: "عنوان الوظيفة (بالعربية)",
    adminJobTitleEn: "عنوان الوظيفة (بالإنجليزية)",
    adminCompany: "الشركة أو المنصة",
    adminSalaryUsd: "الدخل التقديري بالدولار $",
    adminJobType: "نوع وطبيعة العمل",
    adminPayoutMethod: "طرق السحب والتحويل المالي المتاحة",
    adminSkillsReq: "المهارات المطلوبة (مفصولة بفواصل)",
    adminJobDescription: "وصف الوظيفة والمهام المطلوبة",
    adminArabUnisNav: "دليل الجامعات العربية",
    adminGlobalUnisNav: "دليل الجامعات العالمية",
    adminArabUnisManagement: "إدارة واستعراض الجامعات العربية والمنح",
    adminGlobalUnisManagement: "إدارة واستعراض الجامعات العالمية وبوابات المنح",
    adminExploreArabUnisDesc: "استعراض والتحكم في جامعات 8 دول عربية ومعدلات القبول وروابط البوابات الرسمية",
    adminExploreGlobalUnisDesc: "استعراض كبرى الدول المانحة العالمية والمواعيد السنوية وشروط القبول",
    // Notifications
    notifMatchTitle: "مطابقة ذكية جديدة",
    notifMatchBody: "وجدنا 3 منح تطابق مهاراتك بناءً على أحدث الأخبار العالمية.",
    notifDeadlineTitle: "اقترب الموعد النهائي",
    notifDeadlineBody: "منحة تشيفنينغ تنتهي خلال 14 يوماً. لا تفوّت الفرصة.",
    notifNewsTitle: "خبر يربطك بفرصة",
    notifNewsBody: "الاتحاد الأوروبي وسّع برامج إيراسموس — تحقق من الفرص الجديدة.",
    timeMinutesAgo: "قبل دقائق",
    timeHourAgo: "قبل ساعة",
    time3HoursAgo: "قبل 3 ساعات",
    notifFooter: "الإشعارات تربط الأخبار العالمية بالفرص المناسبة لملفك الشخصي.",
    // Scholarships
    scholarshipsHint: "الفرص مجمّعة من مصادر رسمية عالمية وعربية، ومُرتّبة حسب موقعك واهتماماتك.",
    aiMatchBadge: "مطابقة ذكية جديدة",
    aiMatchBody: "وجدنا 3 منح تطابق مهاراتك بناءً على تحليل أحدث الأخبار العالمية",
    swipeHint: "اسحب لليمين للحفظ • لليسار للتجاهل",
    noMoreScholarships: "انتهت المنح المتاحة",
    noMoreScholarshipsDesc: "سنخبرك حال توفر منح جديدة تناسبك",
    reload: "إعادة التحميل",
    filterAllScholarships: "جميع المنح",
    filterArabScholarships: "المنح العربية",
    filterGlobalScholarships: "المنح العالمية",
    studyLanguage: "لغة الدراسة",
    langArabic: "العربية",
    langEnglish: "الإنجليزية",
    langBoth: "عربي/إنجليزي",
    noScholarshipsCategory: "لا توجد منح في هذا التصنيف حالياً",
    verified: "موثقة",
    manualReview: "مراجعة يدوية",
    matchPercent: "مناسبة لك بنسبة",
    country: "الدولة",
    amount: "المبلغ",
    deadline: "آخر موعد",
    level: "المستوى",
    applyOfficial: "التقديم على الموقع الرسمي",
    applyOfficialNote: "سيتم فتح الموقع الرسمي للجهة المانحة داخل التطبيق لتقديم طلبك مباشرة.",
    sourceLink: "رابط المصدر",
    saved: "تم حفظ المنحة في طلباتك",
    dismissed: "تم تجاهل المنحة",
    // News
    dataSaver: "وضع توفير البيانات (نص فقط)",
    catAll: "الكل",
    catLocal: "محلي",
    catArab: "عربي",
    catGlobal: "عالمي",
    lastUpdated: "آخر تحديث",
    loadingShort: "جارٍ التحميل...",
    newsCount: "خبر",
    openSource: "افتح المصدر",
    // Weather
    searchCityPlaceholder: "ابحث عن طقس مدينة أخرى...",
    search: "بحث",
    cityNotFound: "لم يتم العثور على المدينة",
    weatherFailed: "تعذر تحديث الطقس",
    loadingWeather: "جارٍ تحميل الطقس...",
    // Currency Calculator
    liveGoldCurrency: "حاسبة العملات والذهب الحية",
    calc: "حاسبة",
    currency: "العملات",
    gold: "الذهب",
    from: "من",
    to: "إلى",
    weight: "الوزن (غ)",
    karat: "العيار",
    estValue: "القيمة التقديرية",
    fetchingRates: "جارٍ جلب أحدث الأسعار...",
    liveRatesAt: "أسعار حية — آخر تحديث",
    fetchingGold: "جارٍ جلب سعر الذهب...",
    liveGoldAt: "سعر الذهب الحي — آخر تحديث",
    // Applications
    loading: "جاري التحميل...",
    noApps: "لا توجد طلبات بعد",
    noAppsDesc: "ابدأ بحفظ المنح من قسم \"المنح والفرص\"",
    statusApplied: "متقدّم",
    statusSaved: "محفوظة",
    markApplied: "علّم كمتقدّم",
    markedApplied: "تم وضع علامة كمتقدّم",
    updated: "تم التحديث",
    removed: "تمت الإزالة",
    // Profile
    fullName: "الاسم الكامل",
    location: "الموقع",
    bio: "نبذة",
    education: "التعليم",
    interests: "الاهتمامات الأساسية",
    skills: "المهارات",
    addSkill: "أضف مهارة...",
    noSkills: "لم تُضِف مهارات بعد",
    save: "حفظ التغييرات",
    saving: "جاري الحفظ...",
    saveFailed: "تعذر الحفظ",
    saved2: "تم حفظ ملفك الشخصي",
    edit: "تعديل",
    editProfile: "تعديل الملف الشخصي",
    editProfileDesc: "حدّث بياناتك للحصول على فرص أنسب",
    profileCompletion: "اكتمال الملف الشخصي",
    completeProfileHint: "أكمل بياناتك للحصول على مطابقات أدق للمنح والفرص.",
    personalInfo: "المعلومات الشخصية",
    interestsHint: "تُستخدم لمطابقتك بالمنح والفرص الأنسب لك.",
    yourNameHolder: "اكتب اسمك",
    locationHolder: "المدينة، الدولة",
    bioHolder: "عرّف عن نفسك...",
    eduHolder: "مثال: بكالوريوس هندسة حاسوب، جامعة الملك سعود، 2024",
    eduLabel: "المؤهل التعليمي",
    idCard: "FORAS · ID CARD",
    yourFullName: "اسمك الكامل",
    eduDetailsTitle: "المعلومات التعليمية",
    highSchoolLabel: "المدرسة الثانوية",
    highSchoolHolder: "اسم المدرسة الثانوية...",
    universityLabel: "الجامعة / الكلية",
    universityHolder: "اسم الجامعة أو الكلية...",
    majorLabel: "التخصص الدراسي",
    majorHolder: "التخصص...",
    gpaLabel: "المعدل التراكمي",
    gpaScaleLabel: "السلّم",
    degreeLabel: "الدرجة العلمية",
    degreeSelectHolder: "اختر الدرجة...",
    personalLinksTitle: "الروابط الشخصية",
    noLinksYet: "لا توجد روابط بعد — اضغط أعلاه لإضافة.",
    skillsAndExpTitle: "المهارات والخبرات",
    skillNameHolder: "اسم المهارة (مثال: React.js)",
    noSkillsYet: "لا توجد مهارات مضافة بعد.",
    expYearsLabel: "سنوات الخبرة العملية",
    selectPlaceholder: "اختر...",
    invalidPhoneForCountry: "رقم الهاتف غير صالح لهذه الدولة",
    guestNotice: "أنت تستخدم التطبيق كضيف — بياناتك محفوظة بأمان على جهازك.",
    avatarUpdatedSuccess: "تم تحديث صورتك بنجاح",
    avatarProcessError: "تعذر معالجة الصورة",
    avatarReadError: "تعذر قراءة الصورة",
    avatarUploadError: "تعذر رفع الصورة",
    avatarSaveError: "تعذر حفظ الصورة",
    guestProfileBanner: "👋 أنت تستخدم التطبيق كضيف — سنضيف تسجيل الدخول قريبًا لحفظ بياناتك على السحابة.",
    guestUserLabel: "👤 ضيف",
    // Currency & Finance Hub
    currencyAndGoldHub: "مركز العملات والذهب",
    currencyHubDesc: "عملات عالمية ومحلية، الذهب، والعملات الرقمية في مكان واحد",
    lastUpdatedColon: "آخر تحديث:",
    gold24kPrice: "سعر الذهب (24K)",
    fiatCurrencies: "العملات النقدية",
    priceVsUsd: "السعر مقابل USD",
    cryptoCurrencies: "العملات الرقمية",
    livePrice: "السعر الحي",
    currencyDataSources: "مصادر البيانات: open.er-api.com للعملات و CoinGecko للذهب والعملات الرقمية — تحديث تلقائي كل دقيقة.",
    currencyConverter: "محول العملات",
    goldCalculator: "حاسبة الذهب",
    result: "النتيجة",
    weightInGrams: "الوزن (غ)",
    globalPrice: "السعر العالمي",
    localPrice: "السعر المحلي",
    localPriceFormula: "السعر المحلي = العالمي × سعر صرف {cur} الحي",
    // Economy News
    economyCurrenciesTab: "العملات",
    economyNewsTab: "الأخبار",
    dollarAlertTitle: "تنبيه: ارتفاع الدولار قد يزيد تكلفة منحك الدراسية",
    dollarAlertDesc: "راقب أسعار الصرف قبل تحويل رسوم التقديم أو دفع رسوم الجامعة.",
    howThisAffectsScholarships: "كيف يؤثر هذا على منحك؟",
    dollarIncreaseBullet: "• ارتفاع الدولار = زيادة تكلفة الدراسة بالخارج والرسوم بالعملة الأجنبية.",
    currencyDropBullet: "• انخفاض عملة بلدك = فرصة أفضل للمنح الممولة بالكامل بالدولار أو اليورو.",
    useCalculatorBullet: "• راقب أسعار الصرف الحية لتقدير النفقات الشهرية وتكاليف المعيشة بدقة.",
    // Jobs
    jobsTitle: "فرص العمل",
    jobsSubtitle: "فريلانسر، عن بُعد، ووظائف موثوقة.",
    jobsSearchPlaceholder: "ابحث عن فرصة، شركة، أو مهارة...",
    searchByMyCountry: "ابحث حسب بلدي: {country}",
    countryJobsOnlyHint: "يعرض فقط الفرص المتاحة في بلدك",
    featuredJobs: "فرص مميزة",
    recentJobs: "فرص حديثة",
    noMatchingJobs: "لا توجد فرص مطابقة حالياً — جرّب تعديل الفلتر.",
    perHour: "ساعة",
    perMonth: "شهر",
    perProject: "مشروع",
    newBadge: "جديد",
    jobAddedFavorite: "تمت الإضافة إلى المفضلة",
    jobRemovedFavorite: "تمت الإزالة من المفضلة",
    jobShareSubject: "وجدت هذه الفرصة في تطبيق الفرص: {title} لدى {company}.",
    freelance: "فريلانسر",
    remote: "عن بُعد",
    fullTime: "دوام كامل",
    jobCategoryAll: "الكل",
    jobCategoryProgramming: "برمجة",
    jobCategoryDesign: "تصميم",
    jobCategoryWriting: "كتابة",
    jobCategoryTeaching: "تدريس",
    jobCategoryTrades: "مهني",
    jobCategoryContent: "محتوى",
    jobCategoryEntry: "مبتدئ",
    jobCategoryNew: "جديد",
    jobDetails: "تفاصيل الفرصة",
    applyNow: "التقديم الآن",
    requirements: "المتطلبات",
    jobSkills: "المهارات",
    registrationSteps: "خطوات التسجيل والبدء",
    paymentMethods: "طرق الدفع وسحب الأرباح",
    successStories: "قصص نجاح",
    pros: "المميزات",
    cons: "التحديات",
    averageSalary: "المتوسط",
    commission: "العمولة",
    minWithdrawal: "الحد الأدنى للسحب",
    processingTime: "وقت المعالجة",
    trustLevel: "مستوى الموثوقية",
    estimatedTime: "الوقت المقدر",
    // Sudan Universities Quick Banner
    sudanUniversitiesTitle: "دليل الجامعات السودانية",
    sudanUniversitiesSub: "16 جامعة · نسب القبول · تخصصات · تكاليف",
    jobOpportunitiesTitle: "فرص العمل",
    jobOpportunitiesSub: "مواقع فريلانسر.. وظائف",
    discover: "اكتشف",
    scholarshipsSwipe: "سحب",
    scholarshipsList: "قائمة",
    opportunityResults: "فرصة",
    resultsCount: "نتيجة",
    // Sudan Universities Guide Sheet
    sudanUniGuideTitle: "دليل الجامعات السودانية",
    sudanUniGuideSub: "{n} جامعة — مرتبة حسب متطلبات القبول",
    sudanUniMatchingTitle: "مطابقة ذكية بالنسبة",
    sudanUniMatchingSub: "اكتب نسبتك لنعرض الجامعات المؤهلة لك",
    sudanUniPctPlaceholder: "مثال: 82.5",
    sudanUniOnlyEligible: "المؤهلة فقط",
    sudanUniEligibleResult: "بنسبة {pct}% أنت مؤهل لـ {count} من {total} جامعة",
    sudanUniSearchPlaceholder: "ابحث بالجامعة أو التخصص...",
    sudanUniAllCities: "كل المدن",
    sudanUniAllFaculties: "كل التخصصات",
    sudanUniAllTypes: "كل الأنواع",
    sudanUniGov: "حكومية",
    sudanUniPrivate: "خاصة",
    sudanUniTechnical: "تقنية",
    sudanUniMinReq: "الحد الأدنى",
    sudanUniTuition: "الرسوم",
    sudanUniLiving: "السكن والمعيشة",
    sudanUniAdmissionDocs: "الوثائق والتقديم",
    sudanUniFacultiesList: "الكليات المتاحة",
    sudanUniVisitSite: "زيارة الموقع الرسمي",
    sudanUniEligibleBadge: "مؤهل للقبول ✓",
    sudanUniNotEligibleBadge: "دون الحد الأدنى",
    // AI Advisor & Apply Form & In-App Browser & Notifications & Onboarding
    aiAdvisorTitle: "مستشار الفرص الذكي",
    aiAdvisorConnected: "متصل — مدعوم بالذكاء الاصطناعي",
    aiAdvisorHint: "اسألني عن المنح والقبول! ✨",
    aiAdvisorClear: "مسح المحادثة",
    aiAdvisorPlaceholder: "اكتب سؤالك هنا...",
    aiAdvisorSend: "إرسال",
    applyInAppTitle: "التقديم داخل التطبيق",
    fullNameRequired: "الاسم الكامل *",
    fullNamePlaceholder: "اكتب اسمك الكامل",
    emailRequired: "البريد الإلكتروني *",
    phoneOptional: "رقم الهاتف",
    motivationLetterRequired: "رسالة الدوافع *",
    motivationPlaceholder: "لماذا تتقدم لهذه المنحة؟ ما هي أهدافك؟",
    fillAllRequiredFields: "الرجاء تعبئة جميع الحقول المطلوبة",
    saveApplicationFailed: "تعذر حفظ الطلب",
    applicationSubmittedSuccess: "تم إرسال طلبك بنجاح",
    officialWebsite: "الموقع الرسمي",
    openInBrowser: "فتح بالمتصفح",
    openingOfficialPage: "جاري فتح الصفحة الرسمية...",
    externalPolicyNote: "إذا لم تظهر الصفحة، فذلك بسبب سياسة أمان الموقع التي تفضل الفتح الخارجي.",
    openNow: "فتح الآن",
    officialSourceGuaranteed: "تطبيق الفرص يضمن لك الوصول إلى المصادر والبوابات الرسمية المعتمدة دائماً.",
    newWindow: "نافذة جديدة",
    markAllRead: "تعليم الكل كمقروء",
    clearAllNotifs: "مسح الكل",
    notifSwipeHint: "اسحب الإشعار لليمين أو اليسار للإزالة",
    noNotificationsYet: "لا توجد إشعارات حالياً",
    notificationsEmptyHint: "احفظ منحاً في «طلباتي» لتصلك تنبيهات المواعيد النهائية تلقائياً.",
    source: "المصدر",
    open: "فتح",
    onboarding1Title: "بطاقات المنح الذكية",
    onboarding1Desc: "اسحب لليمين لحفظ المنحة، ولليسار لتجاهلها. واجهة سريعة وجذابة تجعل اكتشاف الفرص متعة.",
    onboarding2Title: "أخبار العالم والمركز الاقتصادي",
    onboarding2Desc: "ابقَ على اطلاع بأحدث الأخبار العالمية والمحلية، الرياضة، الاقتصاد، ومؤشرات السوق في مكان واحد.",
    onboarding3Title: "ذكاء اصطناعي يربط الفرص",
    onboarding3Desc: "نحلل الأخبار العالمية ونربطها بفرص منح حقيقية تناسب تخصصك ومهاراتك تلقائياً.",
    skip: "تخطي",
    next: "التالي",
    getStarted: "ابدأ الآن",
    // Privacy & Security page
    privacySection: "الخصوصية والأمان",
    backToSettings: "العودة إلى الإعدادات",
    locationShare: "مشاركة الموقع الجغرافي",
    locationShareDesc: "يُستخدم لتحديد الدولة، العملة المحلية، والفرص القريبة منك.",
    hideProfile: "إخفاء بيانات الملف الشخصي",
    hideProfileDesc: "إخفاء معلوماتك عن مستخدمي التطبيق الآخرين.",
    twoFA: "المصادقة الثنائية (2FA)",
    twoFADesc: "طبقة حماية إضافية لحسابك.",
    setUp: "إعداد",
    twoFASoon: "ميزة المصادقة الثنائية ستتوفر قريباً.",
    locationDisabledToast: "تم إيقاف مشاركة الموقع. لن يتم استخدام GPS.",
    locationEnabledToast: "تم تفعيل مشاركة الموقع.",
    // About dialog
    aboutTitle: "حول التطبيق",
    aboutVisionLabel: "رؤيتنا",
    aboutVisionBody: "تمكين الشباب العربي من الوصول لأفضل الفرص التعليمية العالمية.",
    aboutTechLabel: "تقنيتنا",
    aboutTechBody: "فلترة ذكية ومطابقة دقيقة باستخدام الذكاء الاصطناعي.",
    aboutTrustLabel: "موثوقيتنا",
    aboutTrustBody: "جميع المصادر رسمية ومحدثة لحظياً.",
    contactUs: "تواصل معنا",
    aboutVersion: "الفُرَص — الإصدار 1.0",
    // Landing
    landingTagline: "بوابتك الذهبية للفرص العالمية",
    landingHeadline: "اكتشف، تقدّم، وحقق طموحك الأكاديمي والعملي",
    landingSubheadline: "منصة الفُرَص تجمع لك أفضل المنح الدراسية العربية والعالمية، وفرص العمل اون لاين، مع مطابقة ذكية تبني على ملفك الشخصي.",
    landingCtaPrimary: "ابدأ الآن مجاناً",
    landingCtaSecondary: "تسجيل الدخول",
    landingFeaturesTitle: "لماذا منصة الفُرَص؟",
    landingFeature1Title: "مصادر موثوقة ومطابقة ذكية",
    landingFeature1Body: "لجميع المنح الدراسية العربية والعالمية من جهات رسمية وخوارزمية AI تربط مهاراتك واهتماماتك بالفرص الأنسب لك فوراً.",
    landingFeature2Title: "دليل الجامعات العربية والعالمية",
    landingFeature2Body: "لاستكشاف الجامعات والمنح الحكومية في 8 دول عربية وكبرى الدول الأجنبية المانحة حول العالم مع مطابقة المؤهلات.",
    landingFeature3Title: "وظائف دولية وعمل عن بعد",
    landingFeature3Body: "لفرص مهنية احترافية بالدولار تناسب مختلف المهارات من شركات عالمية.",
    landingFeature4Title: "منشئ السيرة الذاتية الاحترافية (CV Builder)",
    landingFeature4Body: "لبناء سيرة ذاتية بتنسيقات متوافقة مع أنظمة الفرز الآلي (ATS) وتحميلها بصيغة PDF.",
    landingFeature5Title: "الأخبار والعملات الرقمية",
    landingFeature5Body: "كل الأخبار العربية والعالمية مع متابعة حية لأسعار العملات والذهب والعملات الرقمية.",
    landingWhyTitle: "رسالتنا ورؤيتنا",
    landingWhy1Title: "طموح بلا حدود",
    landingWhy1Body: "رؤيتنا هي تمكين كل طالب وخريج عربي من الوصول لأرقى الجامعات العالمية وأفضل فرص العمل.",
    landingWhy2Title: "مطابقة ذكية بالذكاء الاصطناعي",
    landingWhy2Body: "نستخدم تقنيات متطورة لربط ملفك الشخصي بالمنحة المثالية والوظيفة المناسبة لك.",
    landingWhy3Title: "مصادر موثوقة 100%",
    landingWhy3Body: "نضمن لك الوصول إلى بيانات دقيقة ومحدثة من الجهات والجامعات الرسمية مباشرة.",
    landingContactSupport: "تواصل مع فريق الدعم",
    landingScholarshipsTitle: "أقوى وأحدث المنح المعتمدة",
    landingScholarshipsSubtitle: "محدثة تلقائياً وتزامناً مع أحدث الفرص الموثقة في المنصة",
    landingFreelanceTitle: "أحدث فرص العمل الحر وعن بُعد",
    landingFreelanceSubtitle: "مشاريع ووظائف عالمية موثوقة بدخل بالدولار تناسب البرمجة، التصميم، الترجمة، والمهام الرقمية",
    landingFreelanceViewAll: "استكشف كافة وظائف العمل الحر",
    landingArabHubTitle: "دليل الجامعات العربية والعالمية",
    landingArabHubSubtitle: "استكشف بوابات الجامعات والمنح المعتمدة عبر 8 دول عربية وكبرى الدول المانحة عالمياً",
    landingArabHubViewAll: "تصفح الدليل الأكاديمي",
    landingExploreHub: "دخول ركن الدولة",
    landingGlobalHubTitle: "ركن الجامعات العالمية والمنح الدولية",
    landingGlobalHubSubtitle: "استكشف بوابات المنح السنوية المضمونة ومواعيد التقديم وشروط القبول في كبرى الدول العالمية",
    landingGlobalHubViewAll: "استكشف جميع الدول والجامعات العالمية",
    landingViewAll: "استعرض جميع المنح",
    landingFooter: "© 2026 الفُرَص — جميع الحقوق محفوظة",
  },
  en: {
    settings: "Settings",
    darkMode: "Dark mode",
    accountSettings: "Account settings",
    privacy: "Privacy & Security",
    about: "About",
    clearCache: "Clear cache",
    shareApp: "Share app",
    logout: "Sign out",
    language: "Language",
    arabic: "العربية",
    english: "English",
    notifications: "Notifications",
    confirmLogout: "Confirm sign out",
    confirmLogoutDesc: "Are you sure you want to sign out?",
    yesLogout: "Yes, sign out",
    cancel: "Cancel",
    privacyTitle: "Privacy & Security Policy",
    privacyBody:
      "We are committed to protecting your personal data. We never share your information with third parties without consent. Sensitive data is stored encrypted, and your email is used only for sign-in and notifications. You can delete your account and data at any time from account settings.",
    settingsPreferencesGroup: "Preferences & Display",
    settingsAccountGroup: "Account & Security",
    settingsDataGroup: "Data & Storage",
    settingsAboutGroup: "About & Support",
    settingsCurrency: "Local Currency",
    settingsCurrencyDesc: "Display amounts in your preferred currency",
    settingsLanguageDesc: "Switch language between Arabic and English",
    settingsDarkDesc: "Luxury gold dark theme enabled by default",
    settingsTextOnly: "Data Saver Mode",
    settingsTextOnlyDesc: "Reduce data usage and accelerate browsing",
    settingsAccountDesc: "Manage profile and personal information",
    settingsPrivacyDesc: "Location permissions, visibility, and security",
    settingsAdminDesc: "Manage scholarships, jobs, and universities",
    settingsCacheDesc: "Free up temporary cache on your device",
    settingsShareDesc: "Share Al-Foras with friends & colleagues",
    settingsAboutDesc: "Vision, version, and contact information",
    settingsGuestAccount: "User Account",
    settingsActiveBadge: "Active",
    settingsSelectCurrency: "Select Preferred Currency",
    settingsPersona: "Profile Persona Archetype",
    settingsPersonaDesc: "Tailor displayed fields for students/scholars or professionals/freelancers",
    settingsPersonaStudent: "Student & Scholar",
    settingsPersonaStudentDesc: "Highlight academic degrees, university, and GPA",
    settingsPersonaPro: "Professional & Freelancer",
    settingsPersonaProDesc: "Highlight years of experience, skills, and portfolio",
    close: "Close",
    // Tabs
    tabScholarships: "Scholarships",
    tabNews: "News & Economy",
    tabCurrency: "Currency",
    tabApplications: "My Applications",
    tabProfile: "Profile",
    tabJobs: "Jobs",
    tabArabUnis: "Arab & World Unis",
    // Arab and Global universities
    arabUniTitle: "Arab & World Universities Guide",
    arabUniSubtitle: "Comprehensive directories for accredited universities and government scholarships in 8 Arab nations and major donor countries worldwide.",
    academicHubTabArab: "Arab Universities Hub",
    academicHubTabGlobal: "World Universities Hub",
    arabUnisSubTab: "Arab Universities",
    globalUnisSubTab: "World Universities",
    quickUnisGuideTitle: "Universities Guide",
    globalUnisHeading: "Global Donor Portals & International Scholarships",
    globalUnisSubheading: "In-depth guide to major international government scholarships, annual application windows, admission criteria, and official portals.",
    globalGuaranteedTier: "Annual Guaranteed Full Funding",
    globalPeriodicTier: "Periodic, Elite & Competitive Scholarships",
    globalApplicationWindow: "Annual Application Window",
    globalFundingType: "Funding & Coverage Type",
    globalLanguages: "Languages of Study",
    globalDegrees: "Available Degrees",
    globalPortals: "Official Portals",
    globalTopUnis: "Top Globally Accredited Universities",
    globalCoverageList: "Benefits & Financial Coverage",
    arabUniSearch: "Search by university, country or city...",
    arabUniMatchTitle: "Smart match by your percentage",
    arabUniPctPlaceholder: "Your %",
    arabUniEligibleOnly: "Eligible only",
    arabUniEligibleCount: "You qualify for {n} universities based on your percentage.",
    arabUniAllCountries: "All countries",
    arabUniAllFaculties: "All faculties",
    arabUniResults: "{n} results",
    arabUniGov: "Public",
    arabUniPrivate: "Private",
    arabUniHasScholarships: "Scholarships",
    arabUniMin: "Minimum",
    arabUniEmpty: "No universities match your search.",
    arabUniCity: "City",
    arabUniType: "Type",
    arabUniLanguage: "Language of study",
    arabUniFaculties: "Faculties & majors",
    arabUniVisit: "Visit official website",
    arabUniCountriesTitle: "Choose a country",
    arabUniYourCountry: "Your country",
    arabUniUnisCount: "{n} universities",
    arabUniBack: "Back to countries",
    arabUniCompare: "Compare",
    arabUniCompareHint: "Pick up to 3 universities to compare",
    arabUniCompareOpen: "Show comparison ({n})",
    arabUniClear: "Clear selection",
    arabUniTuition: "Tuition fees",
    arabUniLiving: "Living cost",
    arabUniSeasons: "Application windows",
    arabUniDocs: "Required documents",
    arabUniSteps: "Application steps",
    arabUniMap: "View on map",
    arabUniOverview: "Overview",
    arabUniCosts: "Costs",
    arabUniAdmission: "Admission",
    arabUniSmartMatchDesc: "Enter your score or percentage to view eligible institutions meeting your profile",
    arabUniSmartMatchQualified: "With {pct}%, you qualify for {eligible} of {total} universities {scope}",
    arabUniAllScope: "across Arab nations",
    arabUniInCountry: "in {country}",
    arabUniBackToCountries: "Back to Countries list",
    arabUniScholarshipsAvailable: "Scholarships Available",
    arabUniInstitutionsCount: "Includes {count} accredited universities · Minimum admission starts from {min}%",
    arabUniOfficialPortalsBanner: "Accredited Government Portals",
    arabUniScholarshipTypeLabel: "Scholarship Types:",
    arabUniOfficialPortalsLabel: "Official Portals & Inquiries:",
    arabUniAllMajorsOption: "All Faculties & Majors",
    arabUniAllUnisOption: "All Universities",
    arabUniGovOption: "Public / State",
    arabUniPrivOption: "Private",
    arabUniTechOption: "Technical",
    arabUniClearFilters: "Clear Filters",
    arabUniSelectedCompare: "{count} of 3 selected",
    arabUniTuitionCoveredGov: "Fully covered by government grants or nominal fees",
    arabUniLivingCoveredStipend: "Covered with regular monthly government stipend",
    arabUniMainCycle: "Main Cycle: {window} · Supplementary intake subject to academic calendar",
    arabUniAssociatedGovGrant: "Associated Government Scholarship & Coverage",
    arabUniRequiredDocsTitle: "Required Documents",
    arabUniApplicationStepsTitle: "Application Steps",
    arabUniLocationMapBtn: "Map",
    arabUniOfficialSiteBtn: "Official Website",
    arabUniDirectScholarshipFilter: "Active Direct Grants 🔥",
    arabUniAlumniFilter: "Notable Alumni 🎓",
    arabUniPresenceFilter: "Arab Presence 👥",
    arabUniSearchPlaceholder: "Search by university, major, grant, or pioneers...",
    // Global Universities Tab Keys
    globalUniSelectCountry: "Select Global Country",
    globalUniCountryCount: "{n} countries",
    globalUniAllCountries: "All Donor Nations",
    globalUniCategoryAll: "All",
    globalUniFilterAll: "All Universities",
    globalUniFilterScholarships: "Active Grants 🔥",
    globalUniFilterAlumni: "Notable Alumni 🎓",
    globalUniFilterPresence: "Arab Presence 👥",
    globalUniDirectGrantBadge: "Active Direct Grant 🔥",
    globalUniCategoryArabPopular: "Top Arab Student Destinations",
    globalUniCategoryEuGrants: "EU & Full-Funding Grants",
    globalUniCategoryAnglophone: "Premier Anglophone & Ivy League",
    globalUniCategoryEurasiaEastAsia: "Eurasia, East Asia & Southern Europe",
    globalUniCategoryAdvancedEurope: "Advanced Western Europe & Oceania",
    globalUniGuaranteed: "Annual Guaranteed Grants",
    globalUniPeriodic: "Periodic / Elite",
    globalUniGuaranteedBadge: "Annual Guaranteed",
    globalUniAccreditedUnis: "accredited universities",
    globalUniScholarshipsAvailable: "Scholarships Available",
    globalUniSearchPlaceholder: "Search university name, city, or specialization...",
    globalUniFoundUnis: "Found {count} accredited universities",
    globalUniBannerDesc: "Includes {count} prestigious global universities · {funding}",
    globalUniLeadingBadge: "World Leading",
    globalUniScholarshipEligible: "Government Scholarship Eligible",
    globalUniFundingStatus: "Funding Coverage",
    globalUniEligibleApply: "Eligible to Apply ✓",
    globalUniWebsite: "Website",
    globalUniFullDetails: "Full Details",
    globalUniNoResults: "No universities match your search.",
    globalUniResetSearch: "Reset search",
    globalUniCityLabel: "City",
    globalUniMinAdmissionLabel: "Min. Admission",
    globalUniInstTypeLabel: "Type",
    globalUniInstTypeValue: "Accredited Public / State",
    globalUniLangLabel: "Instruction Language",
    globalUniTuitionLabel: "Tuition Fees",
    globalUniTuitionCovered: "Fully covered by government grants or nominal fees",
    globalUniLivingLabel: "Living Cost & Stipend",
    globalUniLivingCovered: "Covered with regular monthly government stipend",
    globalUniDeadlinesTitle: "Application Deadlines",
    globalUniDeadlinesDesc: "Main Cycle: {window} · Supplementary intake subject to academic calendar",
    globalUniAssociatedScholarshipTitle: "Associated Government Scholarship:",
    globalUniFacultiesTitle: "Faculties & Disciplines",
    globalUniDocsTitle: "Required Documents",
    globalUniStepsTitle: "Application Steps",
    globalUniLocationMap: "Map",
    globalUniVisitOfficialSite: "Official Website",
    // Admin Dashboard Keys
    adminTitle: "Al-Foras Management Control Panel",
    adminActiveSession: "Active Session: {name} ({role})",
    adminActiveSessionLabel: "Active Session:",
    adminSuperAdminRole: "Super Admin",
    adminModeratorRole: "Content Moderator",
    adminSignInPrompt: "Sign in to manage opportunities and review submissions",
    adminLoginPrompt: "Sign in to continue",
    adminLockLogout: "Lock & Sign Out",
    adminLoginTitle: "Admin & Moderator Sign In",
    adminLoginSubtitle: "Enter verified email and credentials to proceed",
    adminLoginDesc: "Enter official verified credentials to access control panel",
    adminIdentifierLabel: "Email or Username",
    adminEmailOrUsername: "Email or Username",
    adminPasswordLabel: "Password / PIN",
    adminPasswordOrPin: "Password / PIN",
    adminLoginSubmit: "Unlock Control Panel",
    adminUnlockBtn: "Unlock Control Panel",
    adminForgotPassword: "Forgot Password?",
    adminRecoveryTitle: "Admin Password Recovery",
    adminRecoveryDesc: "A secure one-time verification OTP will be sent to the official unified email alforas.one@gmail.com",
    adminSendOtpBtn: "Send Recovery OTP",
    adminOtpSentMsg: "A 6-digit security code has been dispatched to the official unified email.",
    adminEnterOtpLabel: "Enter 6-Digit Security OTP",
    adminVerifyOtpBtn: "Verify Code & Proceed",
    adminNewPasswordLabel: "Set New Password",
    adminConfirmNewPasswordLabel: "Confirm New Password",
    adminSaveNewPasswordBtn: "Save New Password & Reset Lockout",
    adminLockoutTitle: "🚨 Security Intrusion Lockout Active",
    adminLockoutNotice: "Maximum allowed attempts exceeded (3 failed tries). Attempted credentials have been logged in the security audit trail and reported to the Super Admin.",
    adminLockedNeedAdminUnlock: "Login is currently disabled until unlocked by the Super Admin or recovered via official email OTP.",
    adminAttemptsLeft: "{count} attempt(s) remaining before security lockout",
    adminOneAttemptLeft: "Warning: 1 attempt left before permanent security lockout",
    adminSearchMenu: "Search menu items...",
    adminSelectAll: "Select All",
    adminDeselectAll: "Deselect All",
    adminSelectAllLabel: "Select All",
    adminAddScholarship: "Add New Scholarship",
    adminAddScholarshipBtn: "Add New Scholarship",
    adminAddJob: "Add Remote / Freelance Job",
    adminAddJobBtn: "Add Remote / Freelance Job",
    adminActiveScholarshipsCount: "Active Scholarships ({count} items)",
    adminRangeHint: "💡 Shift + Click to select a range of items",
    adminNoScholarships: "No scholarships found in this section",
    adminNoScholarshipsDesc: "You can add a new scholarship by clicking the button above.",
    adminEdit: "Edit",
    adminArchive: "Archive",
    adminActiveJobsCount: "Active Remote & Freelance Jobs ({count} items)",
    adminNoJobs: "No freelance opportunities recorded yet",
    adminVaultTitle: "Archive Vault & Trash ({count} items)",
    adminVaultHint: "Secure soft-delete storage with instant restore capability",
    adminVaultEmpty: "Archive vault is empty",
    adminVaultEmptyDesc: "All deleted items appear here safely to prevent accidental data loss.",
    adminRestore: "Restore",
    adminDeletePermanently: "Delete Permanently",
    adminDangerZone: "Danger Zone - Empty Vault Permanently",
    adminDangerZoneDesc: "This action will permanently delete all archived items without recovery. Please proceed with caution.",
    adminTypeDeleteConfirm: "Type DELETE to confirm emptying vault",
    adminEmptyVaultBtn: "Empty Vault Permanently",
    adminAiUrlExtractor: "AI Smart URL Parser for Grants & Jobs",
    adminAiUrlExtractorDesc: "Paste any official grant or job link; AI will extract and structure all details automatically",
    adminExtractBtn: "Extract & Process Data",
    adminExtractedReady: "Data extracted and ready for review & publish",
    adminApprovePublishNow: "Approve & Publish Now",
    adminTeamTitle: "Verified Admin & Moderator Team",
    adminAuditLogTitle: "Security Audit & Activity Logs ({count} events)",
    adminPendingTitle: "Pending Review Submissions ({count} items)",
    adminNoPending: "No pending review submissions",
    adminApprovePublish: "Approve & Publish",
    adminBackupTitle: "Export Full Data Backup",
    adminBackupDesc: "Download a structured JSON backup of all scholarships, jobs, security logs, and archives for safekeeping.",
    adminDownloadBackupBtn: "Download Full Backup (JSON)",
    adminItemsSelected: "{count} item(s) selected",
    adminClearSelection: "Clear Selection",
    adminRestoreSelected: "Restore Selected ({count})",
    adminArchiveSelected: "Archive Selected ({count})",
    adminDeleteModalTitle: "Security Confirmation to Archive Item",
    adminDeleteModalDesc: "As a moderator, «{title}» will be archived and the Super Admin will be notified immediately.",
    adminCancel: "Cancel",
    adminConfirmArchive: "Confirm Archive",
    adminEditScholarshipTitle: "Add / Edit Scholarship Record",
    adminEditScholarshipSubtitle: "Configure scholarship scope (Arab / Global), financial coverage, and link to universities",
    adminEditScholarshipDesc: "Enter all academic criteria, admission rates, and financial coverage details",
    adminScholarshipScopeLabel: "Scholarship Scope & Category",
    adminScopeArabOption: "Arab Region Scholarship (MENA)",
    adminScopeGlobalOption: "Global Donor Scholarship (Major Foreign Nations)",
    adminScopeGeneralOption: "General International Scholarship",
    adminHostCountryLabel: "Host Country",
    adminSelectCountryPlaceholder: "-- Select Country --",
    adminCustomCountryLabel: "Or Enter Country Manually",
    adminInstitutionLabel: "University / Institution Name (Arabic)",
    adminInstitutionEnLabel: "University / Institution Name (English)",
    adminStudyLanguageLabel: "Instruction Language",
    adminStudyLangAr: "Arabic",
    adminStudyLangEn: "English",
    adminStudyLangBoth: "Arabic / English",
    adminScholarshipTitleAr: "Scholarship Title (Arabic)",
    adminScholarshipTitleEn: "Scholarship Title (English)",
    adminTitleAr: "Scholarship Title (Arabic)",
    adminTitleEn: "Scholarship Title (English)",
    adminCountryUniversity: "Host Country & University",
    adminDegreeLevelLabel: "Degree Level",
    adminDegreeLevel: "Degree Level",
    adminFundingCoverageLabel: "Funding & Coverage Type",
    adminFundingCoverage: "Funding & Coverage Type",
    adminDeadlineLabel: "Application Deadline",
    adminDeadline: "Application Deadline",
    adminApplyUrlLabel: "Official Direct Application URL",
    adminApplyUrl: "Official Direct Application URL",
    adminLangReqLabel: "Language Requirements (IELTS / TOEFL)",
    adminLanguageReq: "Language Requirements (IELTS / TOEFL)",
    adminDescLabel: "Scholarship Description, Benefits & Majors",
    adminDescriptionBenefits: "Scholarship Description & Financial Benefits",
    adminCustomFieldsSection: "Dynamic Custom Fields & Criteria",
    adminCustomFieldsTitle: "Dynamic Custom Fields & Criteria",
    adminAddFieldBtn: "Add Custom Field",
    adminAddField: "Add Custom Field",
    adminCancelBtn: "Cancel",
    adminSavePublishBtn: "Save & Publish Scholarship",
    adminSavePublish: "Save & Publish Scholarship",
    adminSaveSuccessToast: "Scholarship record saved and updated successfully",
    adminArchiveConfirmTitle: "Security Confirmation to Archive Item",
    adminArchiveConfirmPrompt: "You are about to archive this item. It will be moved to the archive and super admin will be notified.",
    adminConfirmArchiveBtn: "Confirm Archive & Notify",
    adminEditJobTitle: "Add / Edit Remote & Freelance Job",
    adminEditJobDesc: "Configure USD earning details, required skills, and payout methods",
    adminJobTitleAr: "Job Title (Arabic)",
    adminJobTitleEn: "Job Title (English)",
    adminCompany: "Company or Platform",
    adminSalaryUsd: "Estimated Earning (USD $)",
    adminJobType: "Job Nature & Type",
    adminPayoutMethod: "Available Payout & Withdrawal Methods",
    adminSkillsReq: "Required Skills (Comma separated)",
    adminEditJobDescription: "Job Description & Responsibilities",
    adminTeamTitle: "Approved Team & Moderators",
    adminTeamDesc: "Manage moderators, role permissions, and security constraints",
    adminNoPermissionToast: "You do not have permission to perform this action. Contact the Super Admin.",
    adminPermissionDenied: "Permission denied. Action restricted.",
    adminCanEditLabel: "Permission to Edit & Modify",
    adminCanDeleteLabel: "Permission to Delete & Archive",
    adminCanCreateLabel: "Permission to Add New Items",
    adminCanAutoPublishLabel: "Auto-Publish without Review",
    adminPermissionsUpdatedToast: "Moderator permissions updated successfully",
    adminArabUnisNav: "Arab Universities Guide",
    adminGlobalUnisNav: "World Universities Guide",
    adminArabUnisManagement: "Manage & Browse Arab Universities",
    adminGlobalUnisManagement: "Manage & Browse Global Universities",
    adminExploreArabUnisDesc: "Explore and oversee universities and government scholarships across 8 Arab nations",
    adminExploreGlobalUnisDesc: "Explore major international donor countries, annual deadlines, and requirements",
    // Notifications
    notifMatchTitle: "New smart match",
    notifMatchBody: "We found 3 scholarships matching your skills based on the latest global news.",
    notifDeadlineTitle: "Deadline approaching",
    notifDeadlineBody: "Chevening scholarship closes in 14 days. Don't miss it.",
    notifNewsTitle: "News linked to an opportunity",
    notifNewsBody: "The EU expanded Erasmus programs — check the new opportunities.",
    timeMinutesAgo: "minutes ago",
    timeHourAgo: "an hour ago",
    time3HoursAgo: "3 hours ago",
    notifFooter: "Notifications connect global news to opportunities matching your profile.",
    // Scholarships
    scholarshipsHint: "Opportunities aggregated from official global and Arab sources, sorted by your location and interests.",
    aiMatchBadge: "New smart match",
    aiMatchBody: "We found 3 scholarships matching your skills based on the latest global news.",
    swipeHint: "Swipe right to save • left to dismiss",
    noMoreScholarships: "No more scholarships",
    noMoreScholarshipsDesc: "We'll notify you when new ones become available",
    reload: "Reload",
    filterAllScholarships: "All Scholarships",
    filterArabScholarships: "Arab Scholarships",
    filterGlobalScholarships: "Global Scholarships",
    studyLanguage: "Study language",
    langArabic: "Arabic",
    langEnglish: "English",
    langBoth: "Arabic/English",
    noScholarshipsCategory: "No scholarships in this category right now",
    verified: "Verified",
    manualReview: "Manual review",
    matchPercent: "Match",
    country: "Country",
    amount: "Amount",
    deadline: "Deadline",
    level: "Level",
    applyOfficial: "Apply on official website",
    applyOfficialNote: "The official website will open inside the app for you to apply directly.",
    sourceLink: "Source link",
    saved: "Scholarship saved to your applications",
    dismissed: "Scholarship dismissed",
    // News
    dataSaver: "Data saver (text only)",
    catAll: "All",
    catLocal: "Local",
    catArab: "Arab",
    catGlobal: "Global",
    lastUpdated: "Updated",
    loadingShort: "Loading...",
    newsCount: "stories",
    openSource: "Open source",
    // Weather
    searchCityPlaceholder: "Search weather for another city...",
    search: "Search",
    cityNotFound: "City not found",
    weatherFailed: "Couldn't update weather",
    loadingWeather: "Loading weather...",
    // Currency Calculator
    liveGoldCurrency: "Live currency & gold calculator",
    calc: "Calc",
    currency: "Currency",
    gold: "Gold",
    from: "From",
    to: "To",
    weight: "Weight (g)",
    karat: "Karat",
    estValue: "Estimated value",
    fetchingRates: "Fetching latest rates...",
    liveRatesAt: "Live rates — updated",
    fetchingGold: "Fetching gold price...",
    liveGoldAt: "Live gold price — updated",
    // Applications
    loading: "Loading...",
    noApps: "No applications yet",
    noAppsDesc: "Start by saving scholarships from the \"Scholarships\" tab",
    statusApplied: "Applied",
    statusSaved: "Saved",
    markApplied: "Mark as applied",
    markedApplied: "Marked as applied",
    updated: "Updated",
    removed: "Removed",
    // Profile
    fullName: "Full name",
    location: "Location",
    bio: "Bio",
    education: "Education",
    interests: "Core interests",
    skills: "Skills",
    addSkill: "Add a skill...",
    noSkills: "No skills added yet",
    save: "Save changes",
    saving: "Saving...",
    saveFailed: "Couldn't save",
    saved2: "Profile saved",
    edit: "Edit",
    editProfile: "Edit profile",
    editProfileDesc: "Update your details for better matches",
    profileCompletion: "Profile completion",
    completeProfileHint: "Complete your details for sharper scholarship matches.",
    personalInfo: "Personal info",
    interestsHint: "Used to match you with the most relevant opportunities.",
    yourNameHolder: "Type your name",
    locationHolder: "City, country",
    bioHolder: "Introduce yourself...",
    eduHolder: "e.g. BSc Computer Engineering, KSU, 2024",
    eduLabel: "Qualification",
    idCard: "FORAS · ID CARD",
    yourFullName: "Your full name",
    eduDetailsTitle: "Educational details",
    highSchoolLabel: "High school",
    highSchoolHolder: "High school name...",
    universityLabel: "University / College",
    universityHolder: "University or college name...",
    majorLabel: "Major / Field of study",
    majorHolder: "Major...",
    gpaLabel: "GPA",
    gpaScaleLabel: "Scale",
    degreeLabel: "Degree",
    degreeSelectHolder: "Select degree...",
    personalLinksTitle: "Personal links",
    noLinksYet: "No links yet — click above to add.",
    skillsAndExpTitle: "Skills & Experience",
    skillNameHolder: "Skill name (e.g. React.js)",
    noSkillsYet: "No skills added yet.",
    expYearsLabel: "Years of experience",
    selectPlaceholder: "Select...",
    invalidPhoneForCountry: "Invalid phone number for this country",
    guestNotice: "You are using the app as a guest — your data is securely stored on your device.",
    avatarUpdatedSuccess: "Your profile photo has been updated",
    avatarProcessError: "Unable to process image",
    avatarReadError: "Unable to read image",
    avatarUploadError: "Unable to upload image",
    avatarSaveError: "Unable to save image",
    guestProfileBanner: "👋 You are using the app as a guest — cloud sync will be available soon.",
    guestUserLabel: "👤 Guest",
    // Currency & Finance Hub
    currencyAndGoldHub: "Currency & Gold Hub",
    currencyHubDesc: "Global and local currencies, gold, and crypto all in one place",
    lastUpdatedColon: "Last updated:",
    gold24kPrice: "Gold Price (24K)",
    fiatCurrencies: "Fiat Currencies",
    priceVsUsd: "Price vs USD",
    cryptoCurrencies: "Cryptocurrencies",
    livePrice: "Live Price",
    currencyDataSources: "Data sources: open.er-api.com for currencies & CoinGecko for gold and crypto — auto-updates every minute.",
    currencyConverter: "Currency Converter",
    goldCalculator: "Gold Calculator",
    result: "Result",
    weightInGrams: "Weight (g)",
    globalPrice: "Global Price",
    localPrice: "Local Price",
    localPriceFormula: "Local Price = Global × live {cur} exchange rate",
    // Economy News
    economyCurrenciesTab: "Currencies",
    economyNewsTab: "News",
    dollarAlertTitle: "Alert: Rising USD may increase study costs abroad",
    dollarAlertDesc: "Monitor exchange rates before transferring application fees or tuition.",
    howThisAffectsScholarships: "How does this affect your opportunities?",
    dollarIncreaseBullet: "• Stronger USD = Higher tuition and living expenses in foreign currency.",
    currencyDropBullet: "• Local currency decline = Better value for fully funded USD/EUR scholarships.",
    useCalculatorBullet: "• Monitor live exchange rates to estimate monthly expenses and living costs accurately.",
    // Jobs
    jobsTitle: "Job Opportunities",
    jobsSubtitle: "Freelance, remote, and verified trusted opportunities.",
    jobsSearchPlaceholder: "Search for opportunity, company, or skill...",
    searchByMyCountry: "Filter by my country: {country}",
    countryJobsOnlyHint: "Only displays opportunities available in your country",
    featuredJobs: "Featured Opportunities",
    recentJobs: "Recent Opportunities",
    noMatchingJobs: "No matching opportunities found — try modifying your filter.",
    perHour: "hour",
    perMonth: "month",
    perProject: "project",
    newBadge: "New",
    jobAddedFavorite: "Added to favorites",
    jobRemovedFavorite: "Removed from favorites",
    jobShareSubject: "I found this opportunity on Al-Foras: {title} at {company}.",
    freelance: "Freelance",
    remote: "Remote",
    fullTime: "Full Time",
    jobCategoryAll: "All",
    jobCategoryProgramming: "Programming",
    jobCategoryDesign: "Design",
    jobCategoryWriting: "Writing",
    jobCategoryTeaching: "Teaching",
    jobCategoryTrades: "Vocational",
    jobCategoryContent: "Content",
    jobCategoryEntry: "Entry-level",
    jobCategoryNew: "New",
    jobDetails: "Opportunity Details",
    applyNow: "Apply Now",
    requirements: "Requirements",
    jobSkills: "Skills",
    registrationSteps: "Registration & Getting Started",
    paymentMethods: "Payout & Withdrawal Methods",
    successStories: "Success Stories",
    pros: "Advantages",
    cons: "Challenges",
    averageSalary: "Average",
    commission: "Commission",
    minWithdrawal: "Min Withdrawal",
    processingTime: "Processing Time",
    trustLevel: "Trust Level",
    estimatedTime: "Estimated Time",
    // Sudan Universities Quick Banner
    sudanUniversitiesTitle: "Sudan Universities Guide",
    sudanUniversitiesSub: "16 universities · admission rates · majors · costs",
    jobOpportunitiesTitle: "Job Opportunities",
    jobOpportunitiesSub: "Freelancer Platforms.. Jobs",
    discover: "Discover",
    scholarshipsSwipe: "Swipe",
    scholarshipsList: "List",
    opportunityResults: "opportunities",
    resultsCount: "results",
    // Sudan Universities Guide Sheet
    sudanUniGuideTitle: "Sudan Universities Guide",
    sudanUniGuideSub: "{n} universities — sorted by admission requirements",
    sudanUniMatchingTitle: "Smart Percentage Match",
    sudanUniMatchingSub: "Enter your percentage to find eligible universities",
    sudanUniPctPlaceholder: "e.g. 82.5",
    sudanUniOnlyEligible: "Eligible only",
    sudanUniEligibleResult: "With {pct}%, you qualify for {count} of {total} universities",
    sudanUniSearchPlaceholder: "Search by university or major...",
    sudanUniAllCities: "All cities",
    sudanUniAllFaculties: "All majors",
    sudanUniAllTypes: "All types",
    sudanUniGov: "Public",
    sudanUniPrivate: "Private",
    sudanUniTechnical: "Technical",
    sudanUniMinReq: "Min Requirement",
    sudanUniTuition: "Tuition Fees",
    sudanUniLiving: "Housing & Living",
    sudanUniAdmissionDocs: "Documents & Admission",
    sudanUniFacultiesList: "Available Faculties",
    sudanUniVisitSite: "Visit Official Website",
    sudanUniEligibleBadge: "Eligible ✓",
    sudanUniNotEligibleBadge: "Below Minimum",
    // AI Advisor & Apply Form & In-App Browser & Notifications & Onboarding
    aiAdvisorTitle: "Smart Opportunity Advisor",
    aiAdvisorConnected: "Online — Powered by AI",
    aiAdvisorHint: "Ask me about scholarships and admissions! ✨",
    aiAdvisorClear: "Clear Chat",
    aiAdvisorPlaceholder: "Type your question here...",
    aiAdvisorSend: "Send",
    applyInAppTitle: "In-App Application",
    fullNameRequired: "Full Name *",
    fullNamePlaceholder: "Enter your full name",
    emailRequired: "Email Address *",
    phoneOptional: "Phone Number",
    motivationLetterRequired: "Motivation Letter *",
    motivationPlaceholder: "Why are you applying for this scholarship? What are your goals?",
    fillAllRequiredFields: "Please fill in all required fields",
    saveApplicationFailed: "Unable to save application",
    applicationSubmittedSuccess: "Your application was submitted successfully",
    officialWebsite: "Official Website",
    openInBrowser: "Open in Browser",
    openingOfficialPage: "Opening official page...",
    externalPolicyNote: "If the page does not appear, the website security policy requires opening in external browser.",
    openNow: "Open Now",
    officialSourceGuaranteed: "Al-Foras guarantees access to verified official portals and sources.",
    newWindow: "New Window",
    markAllRead: "Mark all as read",
    clearAllNotifs: "Clear all",
    notifSwipeHint: "Swipe left or right to dismiss notification",
    noNotificationsYet: "No notifications right now",
    notificationsEmptyHint: "Save scholarships to «My Applications» to receive deadline reminders automatically.",
    source: "Source",
    open: "Open",
    onboarding1Title: "Smart Scholarship Cards",
    onboarding1Desc: "Swipe right to save, swipe left to dismiss. Fast and engaging way to discover opportunities.",
    onboarding2Title: "Global News & Economy Hub",
    onboarding2Desc: "Stay informed with real-time world and local news, sports, economy, and financial indicators.",
    onboarding3Title: "AI That Connects Opportunities",
    onboarding3Desc: "We analyze global news and connect them with real scholarships matching your profile automatically.",
    skip: "Skip",
    next: "Next",
    getStarted: "Get Started",
    // Privacy & Security page
    privacySection: "Privacy & Security",
    backToSettings: "Back to settings",
    locationShare: "Share location",
    locationShareDesc: "Used for country detection, local currency, and nearby opportunities.",
    hideProfile: "Hide profile details",
    hideProfileDesc: "Hide your details from other app users.",
    twoFA: "Two-factor authentication (2FA)",
    twoFADesc: "Extra protection for your account.",
    setUp: "Set up",
    twoFASoon: "Two-factor authentication will be available soon.",
    locationDisabledToast: "Location sharing turned off. GPS will not be used.",
    locationEnabledToast: "Location sharing enabled.",
    // About dialog
    aboutTitle: "About Al-Foras",
    aboutVisionLabel: "Our Vision",
    aboutVisionBody: "Empowering Arab youth to reach the world's best educational opportunities.",
    aboutTechLabel: "Our Technology",
    aboutTechBody: "Smart filtering and precise AI-powered matching.",
    aboutTrustLabel: "Our Trust",
    aboutTrustBody: "All sources are official and updated in real time.",
    contactUs: "Contact Us",
    aboutVersion: "Al-Foras — Version 1.0",
    // Landing
    landingTagline: "Your golden gateway to global opportunities",
    landingHeadline: "Discover, Apply, and Achieve Your Academic & Career Ambitions",
    landingSubheadline: "Al-Foras platform brings you the finest Arab & global scholarships and online job opportunities, with smart AI matching tailored to your profile.",
    landingCtaPrimary: "Get Started — It's Free",
    landingCtaSecondary: "Sign In",
    landingFeaturesTitle: "Why Al-Foras Platform?",
    landingFeature1Title: "Verified Sources & Smart Matching",
    landingFeature1Body: "All Arab & international scholarships from official sources, with an AI algorithm connecting your skills and interests to the best opportunities instantly.",
    landingFeature2Title: "Arab & World Universities Guide",
    landingFeature2Body: "Explore accredited universities and government scholarships across 8 Arab nations and major global donor countries.",
    landingFeature3Title: "Global Jobs & Remote Work",
    landingFeature3Body: "Access professional career opportunities paid in USD matching diverse skillsets from international employers.",
    landingFeature4Title: "Professional CV Builder (ATS-Compliant)",
    landingFeature4Body: "Build modern, ATS-compatible resumes formatted for global standards and download them instantly as PDF.",
    landingFeature5Title: "News & Live Crypto & Currencies",
    landingFeature5Body: "Comprehensive Arab and global news coverage along with real-time exchange rates, gold, and cryptocurrency prices.",
    landingWhyTitle: "Our Mission & Vision",
    landingWhy1Title: "Limitless Ambition",
    landingWhy1Body: "Our vision is to empower every Arab student and graduate to reach top universities and top careers.",
    landingWhy2Title: "AI Smart Matching",
    landingWhy2Body: "Advanced technology connects your profile to the scholarship and career path that fits you best.",
    landingWhy3Title: "100% Verified Sources",
    landingWhy3Body: "We guarantee access to accurate, real-time data straight from official institutions.",
    landingContactSupport: "Contact Support Team",
    landingScholarshipsTitle: "Top Verified Opportunities",
    landingScholarshipsSubtitle: "Automatically synced in real time with the verified listings in the app",
    landingFreelanceTitle: "Top Freelance & Remote Work Opportunities",
    landingFreelanceSubtitle: "Verified global projects and remote jobs paid in USD across tech, design, translation, and digital skills",
    landingFreelanceViewAll: "Explore All Freelance Jobs",
    landingArabHubTitle: "Arab & World Universities Guide",
    landingArabHubSubtitle: "Explore accredited institutions and government scholarship portals across 8 Arab nations and major donor countries worldwide",
    landingArabHubViewAll: "Browse Academic Directory",
    landingExploreHub: "Explore Country Hub",
    landingGlobalHubTitle: "World Universities & International Scholarships Hub",
    landingGlobalHubSubtitle: "Explore annual guaranteed scholarship portals, application windows, and admission requirements worldwide",
    landingGlobalHubViewAll: "Explore All Global Countries & Universities",
    landingViewAll: "Browse All Scholarships",
    landingFooter: "© 2026 Al-Foras — All rights reserved",
  },
};

const ARABIC_COUNTRY_CODES = new Set(
  ["SA","AE","QA","KW","BH","OM","EG","SD","MA","DZ","TN","LY","JO","LB","SY","IQ","YE","PS","KM","MR","SO","DJ"]
);

const detectInitialLang = (): Lang => {
  if (typeof window === "undefined") return "ar";

  // 1. Primary: Check if language was explicitly saved
  const stored = localStorage.getItem("foras-lang") as Lang | null;
  if (stored === "ar" || stored === "en") return stored;

  // 2. Check Country Code from previous geo-sync
  const cc = localStorage.getItem("foras-countrycode");
  if (cc && ARABIC_COUNTRY_CODES.has(cc.toUpperCase())) return "ar";

  // 3. Check Browser Languages
  try {
    const langs = (navigator.languages && navigator.languages.length > 0)
      ? navigator.languages
      : [navigator.language || "ar"];
    const hasArabic = langs.some((l) => l && l.toLowerCase().startsWith("ar"));
    if (hasArabic) return "ar";

    // If English is explicitly the primary preference
    const primary = (langs[0] || "").toLowerCase();
    if (primary.startsWith("en")) return "en";
    if (primary.startsWith("ar")) return "ar";
  } catch {}

  // 4. Check Device Timezone (Arab region timezones default to Arabic)
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone.toLowerCase();
    if (
      tz.includes("khartoum") || tz.includes("cairo") || tz.includes("riyadh") ||
      tz.includes("dubai") || tz.includes("amman") || tz.includes("baghdad") ||
      tz.includes("beirut") || tz.includes("damascus") || tz.includes("kuwait") ||
      tz.includes("qatar") || tz.includes("bahrain") || tz.includes("muscat") ||
      tz.includes("casablanca") || tz.includes("algiers") || tz.includes("tunis") ||
      tz.includes("tripoli") || tz.includes("gaza") || tz.includes("jerusalem") ||
      tz.includes("sanaa") || tz.includes("aden") || tz.includes("sudan")
    ) {
      return "ar";
    }
  } catch {}

  // Fallback default
  return "ar";
};

const Ctx = createContext<LanguageCtx>({
  lang: "ar",
  language: "ar",
  dir: "rtl",
  isRtl: true,
  setLang: () => {},
  toggleLang: () => {},
  t: (k) => k,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() => detectInitialLang());
  const dir: "rtl" | "ltr" = lang === "ar" ? "rtl" : "ltr";
  const isRtl = lang === "ar";

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = dir;
    document.documentElement.setAttribute("dir", dir);
    document.documentElement.setAttribute("lang", lang);
    if (lang === "ar") {
      document.documentElement.classList.add("rtl");
      document.documentElement.classList.remove("ltr");
    } else {
      document.documentElement.classList.add("ltr");
      document.documentElement.classList.remove("rtl");
    }
    try {
      localStorage.setItem("foras-lang", lang);
    } catch {}
  }, [lang, dir]);

  // Bidirectional listener across tabs / storage events / custom dispatches
  useEffect(() => {
    const handleStorage = (e: StorageEvent) => {
      if (e.key === "foras-lang" && (e.newValue === "ar" || e.newValue === "en")) {
        setLangState(e.newValue as Lang);
      }
    };
    const handleCustomLang = (e: Event) => {
      const targetLang = (e as CustomEvent).detail?.lang as Lang | undefined;
      if (targetLang === "ar" || targetLang === "en") {
        setLangState(targetLang);
      }
    };
    window.addEventListener("storage", handleStorage);
    window.addEventListener("foras:langchange", handleCustomLang as EventListener);
    return () => {
      window.removeEventListener("storage", handleStorage);
      window.removeEventListener("foras:langchange", handleCustomLang as EventListener);
    };
  }, []);

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    try {
      localStorage.setItem("foras-lang", l);
      localStorage.setItem("foras-lang-manual", "true");
      document.documentElement.lang = l;
      document.documentElement.dir = l === "ar" ? "rtl" : "ltr";
      document.documentElement.setAttribute("dir", l === "ar" ? "rtl" : "ltr");
      document.documentElement.setAttribute("lang", l);
      window.dispatchEvent(new CustomEvent("foras:langchange", { detail: { lang: l } }));
    } catch {}
  }, []);

  const toggleLang = useCallback(() => {
    setLangState((prev) => {
      const next: Lang = prev === "ar" ? "en" : "ar";
      try {
        localStorage.setItem("foras-lang", next);
        localStorage.setItem("foras-lang-manual", "true");
        document.documentElement.lang = next;
        document.documentElement.dir = next === "ar" ? "rtl" : "ltr";
        document.documentElement.setAttribute("dir", next === "ar" ? "rtl" : "ltr");
        document.documentElement.setAttribute("lang", next);
        window.dispatchEvent(new CustomEvent("foras:langchange", { detail: { lang: next } }));
      } catch {}
      return next;
    });
  }, []);

  const t = useCallback((key: string, params?: Record<string, string | number>) => {
    let text = STRINGS[lang]?.[key] ?? STRINGS["ar"]?.[key] ?? key;
    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        text = text.replace(new RegExp(`\\{${paramKey}\\}`, "g"), String(paramValue));
      });
    }
    return text;
  }, [lang]);

  // touch COUNTRIES so tree-shaker keeps the import side-effect-free
  void COUNTRIES;

  return (
    <Ctx.Provider value={{ lang, language: lang, dir, isRtl, setLang, toggleLang, t }}>
      {children}
    </Ctx.Provider>
  );
};

export const useLanguage = () => useContext(Ctx);
